### ISSUE TITLE
CentOS 6 没法用了

### ISSUE THREAD

**Issue by wjz654** [Lozy/danted#10]
CentOS 6 没法用了 
bash install.sh后没反映

**Comment by wjz654** [comment]
[root@MyCloudServer ~]# bash -x install.sh
+ REQUEST_SERVER=https://raw.github.com/Lozy/danted/master
+ SCRIPT_SERVER=https://public.sockd.info
+ '[' '' == --no-github ']'
+ '[' -s /etc/os-release ']'
+ exit 1

**Comment by Lozy** [comment]
囧~ 看来你的系统木有 /etc/os-release 这个文件~ 
这也是尴尬。

你可以直接用对应系统的脚本

```
wget --no-check-certificate https://raw.github.com/Lozy/danted/master/install_centos.sh -O install.sh
bash -x install.sh
```

**Comment by wjz654** [comment]
我试过这个 wget --no-check-certificate https://public.sockd.info/install_centos.sh -O install_centos.sh
bash install_centos.sh 不行啊 
Ubuntu 14 安装完只有主ip出

**Comment by wjz654** [comment]
Ubuntu 14 安装完并不是 什么ip进什么ip出 而且第一边安装一半就没了 还要再一次bash  install.sh

**Comment by wjz654** [comment]
之前版本还有吗

**Comment by wjz654** [comment]
Jan 19 11:13:05 (1484842385.713150) sockd[28066]: info: sigterm(): exiting on signal 15
Jan 19 11:13:05 (1484842385.713208) sockd[28066]: alert: sockdexit(): terminating
Jan 19 11:13:05 (1484842385.805095) sockd[28072]: info: sigterm(): exiting on signal 15
Jan 19 11:13:05 (1484842385.809443) sockd[28251]: info: sigterm(): exiting on signal 15
Jan 19 11:15:21 (1484842521.314675) sockd[1381]: info: dante/server[1] v1.3.2 running
Jan 19 11:15:21 (1484842521.886981) sockd[1381]: warning: accept(2) failed: Resource temporarily unavailable (errno = 11)
Jan 19 11:15:21 (1484842521.944131) sockd[1381]: warning: accept(2) failed: Resource temporarily unavailable (errno = 11)
Jan 19 11:15:22 (1484842522.272890) sockd[1383]: info: pass(1): udp/udpassociate [: pam%wjx123@0.0.0.0.0 155.94.130.37.53927 -> 107.150.9.13.52716 0.0.0.0.0
Jan 19 11:15:22 (1484842522.436548) sockd[1387]: info: pass(1): tcp/connect [: pam%wjx123@27.185.124.124.57117 155.94.130.37.2016 -> 107.150.9.13.57117 clients2.google.com.80
Jan 19 11:15:22 (1484842522.640051) sockd[1387]: info: pass(1): tcp/connect ]: 0 -> pam%wjx123@27.185.124.124.57117 155.94.130.37.2016 -> 1838, 1838 -> 107.150.9.13.57117 clients2.google.com.80 -> 0: local client error (Connection reset by peer).  Session duration: 0s

**Comment by wjz654** [comment]
直接用对应脚本
+ cat
+ rm /usr/bin/sockd -f
+ ln -s /etc/danted/sbin/sockd /usr/bin/sockd
+ /etc/init.d/sockd adduser '' ''
Adding User For Dante SOCKS 5 daemon: 
 Error: User or password can't be blank
++ ls -l /sbin/init
++ grep systemd
+ '[' -n '' ']'
+ chkconfig --add sockd
+ service sockd restart
Restarting Dante SOCKS 5 daemon: 
Danted Server [ PID.LOST;Unable ] 
/etc/init.d/sockd: line 59: start-stop-daemon: command not found
/etc/init.d/sockd: line 42: start-stop-daemon: command not found
Danted Server [ Start Failed ] 
+ clear
++ ss -ln
++ grep 2016
+ '[' -n '' ']'
+ echo -e '\033[1;31m Dante Server Install Failed! \033[0m'
 Dante Server Install Failed! 
+ echo ''

+ /etc/init.d/sockd -h
 Usage: /etc/init.d/sockd {start|stop|restart|reload|status|state|adduser|deluser|tail}
+ exit 0
Starting Dante SOCKS 5 daemon: 
/etc/init.d/sockd: line 42: start-stop-daemon: command not found
Danted Server [ Start Failed ]

**Comment by Lozy** [comment]
Centos 那个是 start-stop-daemon 没有安装，所以启动不了，我更新一下脚本加上。

Ubuntu的那个可否确认一下配置文件 `cat /etc/danted/sockd.conf`
有 
`external.rotation: same-same`

这一行。

**Comment by wjz654** [comment]
刚才试了下还是
+ /etc/init.d/sockd adduser '' ''
Adding User For Dante SOCKS 5 daemon: 
 Error: User or password can't be blank
++ ls -l /sbin/init
++ grep systemd
+ '[' -n '' ']'
+ chkconfig --add sockd
+ service sockd restart
Restarting Dante SOCKS 5 daemon: 
Danted Server [ PID.LOST;Unable ] 
/etc/init.d/sockd: line 59: start-stop-daemon: command not found
/etc/init.d/sockd: line 42: start-stop-daemon: command not found
Danted Server [ Start Failed ] 
+ clear
++ ss -ln
++ grep 2016
+ '[' -n '' ']'
+ echo -e '\033[1;31m Dante Server Install Failed! \033[0m'
 Dante Server Install Failed! 
+ echo ''

+ /etc/init.d/sockd -h
 Usage: /etc/init.d/sockd {start|stop|restart|reload|status|state|adduser|deluser|tail}
+ exit 0
[root@MyCloudServer network-scripts]# /etc/init.d/sockd start
Starting Dante SOCKS 5 daemon: 
/etc/init.d/sockd: line 42: start-stop-daemon: command not found
Danted Server [ Start Failed ]

**Comment by wjz654** [comment]
Ubuntu的
root@t116071701191336:~# cat /etc/danted/sockd.conf
# Generate by sockd.info
# Generate interface 162.220.13.181
internal: 162.220.13.181  port = 2018
external: 162.220.13.181
# Generate interface 107.150.9.13
internal: 107.150.9.13  port = 2018
external: 107.150.9.13
method: pam none
clientmethod: none
user.privileged: root
user.notprivileged: sockd
logoutput: /var/log/sockd.log

client pass {
        from: 0.0.0.0/0  to: 0.0.0.0/0
}
client block {
        from: 0.0.0.0/0 to: 0.0.0.0/0
}
pass {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        protocol: tcp udp
        method: pam
        log: connect disconnect
}
block {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        log: connect error
}

**Comment by wjz654** [comment]
要修改下吗 加到那一行

**Comment by Lozy** [comment]
hi. 你重新跑下脚本。根据你的反馈，我这边修复了这个bug 哈

```
bash install.sh

``

**Comment by wjz654** [comment]
CentOS 6  还是 Ubuntu的

**Comment by wjz654** [comment]
Ubuntu的 OK了  十分感谢

**Comment by Lozy** [comment]
CentOS 6 重新安装 应该可以适配了

**Comment by mrlongshen** [comment]
Hi @Lozy Sorry to disturb on this topic.
May I ask you something. I dont know how to reach you. No email to email you.
With danted script you make, can I connect from 1 vps at US and another Vps at Singapore ? 
I want redirect all traffic from US server to main server at Singapore. Can this script make it ? 
Lets me know. Thanks.

**Comment by Lozy** [comment]
@mrlongshen 

In my view, you can simply running [rinetd](https://www.boutell.com/rinetd/) to redirect tcp traffic. Otherwise, Iptables(nat) will reach the same. However, this will lost client's ip address.

If you insist to use this sockd to get that, you can try [Redirect Module](https://www.inet.no/dante/doc/latest/redirect.html) configure. Edit the config file /etc/danted/sockd.conf

**Comment by Lozy** [comment]
It looks like Redirect Module is one of the dante's commercial modules. FYI.
