### ISSUE TITLE
Timeout，跪求大佬指点

### ISSUE THREAD

**Issue by GoogleQian** [Lozy/danted#100]
运行的好好地，过了好几个月了，几天突然链接超时，怎么都代理不了，测试qq代理登录，可以连接代理服务器，但是怎么都是超时的

**Comment by GoogleQian** [comment]
Jul  9 13:21:53 (1657344113.654606) sockd[18342]: info: pass(1): tcp/connect ]: 0 -> pam%root@183.17.126.133.47662 172.26.71.240.1080 -> 0, 0 -> 172.26.71.240.47662 ts8.qq.com.8000 -> 0: timeout while waiting for the connect to complete.  Session duration: 30s

**Comment by Lozy** [comment]
大概率是因为GFW。换个节点或者加国内IDC机器做中转

**Comment by GoogleQian** [comment]
多谢大佬，不过当时是连接另外的三方接口超时，然后我就测试qq的结果也不行，后面又用工具测，网页正常可以代理，我曹，结果是三方的服务问题。。。，
