### ISSUE TITLE
你好老大，16号凌晨开始，无法安装您的脚本（系统ubuntu20.04,  Centos 7.9 ），错误如下

### ISSUE THREAD

**Issue by ttagxwr** [Lozy/danted#107]
HTTP request sent, awaiting response... 503 hostname doesn't match against certificate
2022-12-15 18:57:40 ERROR 503: hostname doesn't match against certificate.

谢谢您！

**Comment by Lozy** [comment]
> bash -x install.sh xxxxx

贴一下日志看看？

**Comment by ttagxwr** [comment]
好用了，感谢老大！
