### ISSUE TITLE
你更新版本后，所有子IP出口是主IP。请帮忙看一下

### ISSUE THREAD

**Issue by cfcboy** [Lozy/danted#110]
系统是Debian10，11这样的，之前安装使用一直正常，在你更新版本后，现在也一切正常，启动也正常。

但是连接子IP后，所有子IP的出口都是主IP。

原来连接哪个IP，出口就是哪个IP。

测试过V1.3.2，V1.4.2，V1.4.3几个版本情况一样。

**Comment by Lozy** [comment]
检查一下配置是否有

```
external.rotation: same-same
```

也检查一下iptables-snat 是否做了定制

**Comment by cfcboy** [comment]
后面全部换成CentOS7的系统，一切正常。
那些测试失败，我有条件了再试一下。谢谢。

**Comment by Marchccc** [comment]
> 检查一下配置是否有
> 
> ```
> external.rotation: same-same
> ```
> 
> 也检查一下iptables-snat 是否做了定制

在debian下有效
