### ISSUE TITLE
Server Install Fail 

### ISSUE THREAD

**Issue by BouncingBison** [Lozy/danted#12]
Receiving these errors

"Adding User For Dante SOCKS 5 daemon: 
 Error: User or password can't be blank
Synchronizing state of sockd.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable sockd
Failed to execute operation: Too many levels of symbolic links

 Dante Server Install Failed!"

But has not asked me to input username and password. what have i missed?

**Comment by Lozy** [comment]
Hi， please using like this

`bash install.sh --port=PROT --user=USER --passwd=PASSWD`

**Comment by tododo** [comment]
what host name should be set?

**Comment by Lozy** [comment]
Host name? Can you give me more detail..

**Comment by MichaelRC** [comment]
what are you referring to
