### ISSUE TITLE
service sockd deluser results in an error

### ISSUE THREAD

**Issue by FallenKN** [Lozy/danted#14]
```
root@host:/home/user# service sockd deluser testuser
Clearing User For Testuser SOCKS 5 daemon:
/etc/init.d/sockd: line 212: del_user: command not found
```

Deleting an user is not working

**Comment by Lozy** [comment]
hi, thanks your feedback.

word spell bug fix.  see this: https://github.com/Lozy/danted/commit/28514dd5c3a7ee5d99ec0dff4cc1b633f281989e

You can edit the script file `/etc/init.d/sockd` manually. Otherwise, just reinstall.

**Comment by FallenKN** [comment]
Oh I didn't even notice after checking for this issue haha, thanks for the fast response.
