### ISSUE TITLE
mirror 404

### ISSUE THREAD

**Issue by a7898585** [Lozy/danted#15]
---> Package pam.x86_64 0:0.99.6.2-14.el5_11 set to be updated
http://mirror.scalabledns.com/centos/5/updates/x86_64/repodata/filelists.sqlite.bz2: [Errno 14] HTTP Error 404: Not Found
Trying other mirror.
http://mirrors.xmission.com/centos/5/updates/x86_64/repodata/filelists.sqlite.bz2: [Errno 14] HTTP Error 404: Not Found
Trying other mirror.
http://mirrors.arsc.edu/centos/5/updates/x86_64/repodata/filelists.sqlite.bz2: [Errno 14] HTTP Error 404: Not Found
Trying other mirror.
http://mirror.metrocast.net/centos/5/updates/x86_64/repodata/filelists.sqlite.bz2: [Errno 14] HTTP Error 404: Not Found
Trying other mirror.
http://mirror.linuxfix.com/centos/5/updates/x86_64/repodata/filelists.sqlite.bz2: [Errno 14] HTTP Error 404: Not Found

**Comment by Lozy** [comment]
not related
