### ISSUE TITLE
Issue when installing with more than 1 ip - "Install failed"

### ISSUE THREAD

**Issue by spaceleak** [Lozy/danted#16]
When installing with more than 1 ip I am getting 

`Dante Server Install Failed!`

This only happens when installing with more than one ip.

`--ip="a.a.a.a;b.b.b.b" --port=xxxx --user=xxxx --passwd=xxxx`

The above gives the Dante Server Failed error, if I do it like this without the quotations in the ip option:

`--ip=a.a.a.a;b.b.b.b --port=xxxx --user=xxxx --passwd=xxxx`

I get the error

`Error: User or password can't be blank`

Using CentOS 6.9

Thanks

**Comment by Lozy** [comment]
Hi, I make a update for [this issue](https://github.com/Lozy/danted/commit/3cb834c19851fd64ce5621c00b30bdd6d454d75f#diff-4256d9726e1fa23ee4c1aaeb07f42ffc)

please use ":" instead of ';'.

> --ip=a.a.a.a:b.b.b.b --port=xxxx --user=xxxx --passwd=xxxx

since ';' is a split symbol in bash.

take a try and let me know if it works.
