### ISSUE TITLE
多IP 安装失败

### ISSUE THREAD

**Issue by wjz654** [Lozy/danted#19]
2017-05-17 12:42:09 (21.9 MB/s) - “install_centos.sh” saved [9442/9442]

[root@server823 ~]# bash install_centos.sh
Current Options: 

Loaded plugins: fastestmirror, security
Loading mirror speeds from cached hostfile
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=os error was
14: PYCURL ERROR 6 - "Couldn't resolve host 'mirrorlist.centos.org'"
Error: Cannot find a valid baseurl for repo: base

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
install_centos.sh: line 258: gcc: command not found
Archive:  libpam-pwdfile.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of libpam-pwdfile.zip or
        libpam-pwdfile.zip.zip, and cannot find libpam-pwdfile.zip.ZIP, period.
install_centos.sh: line 267: cd: libpam-pwdfile-master: No such file or directory
[ERROR] pam_pwdfile.so not exist!
Loaded plugins: fastestmirror, security
Loading mirror speeds from cached hostfile
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=os error was
14: PYCURL ERROR 6 - "Couldn't resolve host 'mirrorlist.centos.org'"
Error: Cannot find a valid baseurl for repo: base

centos 6.X 64位

**Comment by wjz654** [comment]
能帮忙看下是什么原因吗

**Comment by Lozy** [comment]
貌似你的网络有问题？看错误是 更新软件源失败了，你试试

> yum update 

是不是一样的错误？ 更换一下比较接近机器的软件源吧~ 如果你的网络有问题的话
