### ISSUE TITLE
debian - wont install

### ISSUE THREAD

**Issue by 343334** [Lozy/danted#20]
Executing /usr/sbin/update-rc.d sockd enable
 Dante Server Install Failed!

 Usage: /etc/init.d/sockd {start|stop|restart|reload|status|state|adduser|deluser|tail|conf|update}

 /etc/init.d/sockd tail
==> /var/log/sockd.log <==

nothing in log.. no real info to say why it failed..  This is just crap as its impossible to diagnose without any info.

**Comment by 343334** [comment]
ok finally found a way to get some errors to show..


1.  sockd[10053]: error: /etc/danted/sockd.conf: problem on line 4 near token "0.0.0.0": external address (0.0.0.0/32) to connect out from cannot be a wildcard address.  Please see the Dante manual for more information     must set to eth0

2. May 17 14:46:28 (1495050388.676930) sockd[10055]: warning: /etc/danted/sockd.conf: problem on line 6 near token "method": keyword "method" is deprecated - assuming the new keyword "socksmethod" was meant.  Please update Dante's config file (/etc/danted/sockd.conf) to use the new keyword as appropriate.  Please see the Dante manual for more information

3. May 17 14:46:28 (1495050388.677084) sockd[10055]: warning: /etc/danted/sockd.conf: problem on line 6 near token "pam": keyword "pam" is deprecated - assuming the new keyword "pam.*" was meant.  Please update Dante's config file (/etc/danted/sockd.conf) to use the new keyword as appropriate.  Please see the Dante manual for more information

4. May 17 14:46:28 (1495050388.677122) sockd[10055]: error: /etc/danted/sockd.conf: problem on line 6 near token "pam": in order to set the given keyword/value, Dante must be linked with an external PAM library at compiletime.  When Dante was compiled, no such linking was done, perhaps due to no usable PAM library being installed on the system at the time.  If a PAM library has since been installed on this system, please rerun ./configure in Dante's source directory, recompile and reinstall Dante.  Please see the Dante manual for more information


Did the author of this script truely test this defaault config it makes on debian???  I dont think so.

**Comment by Lozy** [comment]
I am afraid you have installed the `Dante 1.4.x` (u may use `apt install dante-server` before).

This script is main for `Dante 1.3.2` since this version has external rotation. And, the config file is not compatibled with `Dante 1.4.x`.

If you have double, try `sockd -v` or `danted -v` to check the current version.

If you do want install this script, remove the  `Dante 1.4.x` (apt-get purge dante-server).


> Did the author of this script truely test this default config it makes on debian??? I dont think so.

Please don't say that, I do running testings to release this script.
