### ISSUE TITLE
Not working without user 

### ISSUE THREAD

**Issue by iconis999** [Lozy/danted#22]
Without adding user it is not working. Need to fix this.
I tried without user but not it's working.

**Comment by Lozy** [comment]
1. Edit config file  /etc/danted/sockd.conf

> vim /etc/danted/sockd.conf

change  `method: pam` to `method: none`

like bellow
```
pass {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        protocol: tcp udp
        method: none
        log: connect disconnect
}
```

2. And restart service 

> service sockd restart

**Comment by VTwo-Group** [comment]
hi
this code not work. please fix it.
```
pass {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        protocol: tcp udp
        method: none
        log: connect disconnect
}
```

# Generate by sockd.info
# Generate interface x.x.x.x
internal: x.x.x.x  port = 2016
external: x.x.x.x

method: pam none
clientmethod: none
user.privileged: root
user.notprivileged: sockd
logoutput: /var/log/sockd.log

client pass {
        from: 0.0.0.0/0  to: 0.0.0.0/0
}
client block {
        from: 0.0.0.0/0 to: 0.0.0.0/0
}
pass {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        protocol: tcp udp
        method: none
        log: connect disconnect
}
block {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        log: connect error
}
