### ISSUE TITLE
Short passwords

### ISSUE THREAD

**Issue by aspyatkin** [Lozy/danted#23]
Hello,
When I was creating a user which can connect to my proxy, I noticed that its password in `/etc/danted/sockd.passwd` was hashed using CRYPT, which means that only 8 first characters are used. I patched `sockd` script to use bcrypt but the service refused to start. Consequently, I assumed this is not supported yet.

Is there a way to add bcrypt support?

**Comment by Lozy** [comment]
Hi, please check this [manual page](https://www.inet.no/dante/doc/latest/config/auth.html)

In my view, you can use `bsdauth` -- system account auth. However, using `gssapi` between client and server is better.
