### ISSUE TITLE
multiple ip install failed : Danted Server [ PID.LOST;Unable ]

### ISSUE THREAD

**Issue by abeykp** [Lozy/danted#25]
after installation i get Danted Server [ PID.LOST;Unable ]

if i try to restart i get:
[root@vps433051 ~]# /etc/init.d/sockd restart
Restarting Dante SOCKS 5 daemon:
Danted Server [ PID.LOST;Unable ]
Danted Server [ Start Failed ]

**Comment by abeykp** [comment]
centos 6

**Comment by Lozy** [comment]
Hi, this will be a little complex since I have nothing about this. Please run these commands and paste here wth the result.

```
[ "$(ps -ef | grep sockd | grep -v 'grep' | wc -l)" == "0" ] && echo "[error] sockd process not exists!" || echo "[pass] sockd process running." 

[ ! -f '/etc/danted/sbin/sockd' ] && echo "[error] sockd bin file not exists!" || echo "[pass] sockd bin file."

/etc/danted/sbin/sockd -V && echo "[pass] sockd config file." || echo "[error] sockd config error" 

start-stop-daemon --version && echo "[pass] start-stop-daemon works." || echo "[error] start-stop-daemon error" 

```

**Comment by hiperpoo** [comment]
I'm going to assume from the machine nomenclature that you're using ovh. To get the script to work correctly you first have to configure your failover IP's in /etc/network/interfaces or /etc/network/interfaces.d/interfaces . /etc/network/interfaces Will have a note if you need to use /etc/network/interfaces.d/interfaces .
Follow the guide here https://www.ovh.com/us/g2043.configure_a_failover_ip_with_ubuntu . In my case my interface was ens3 . so for each addition IP I set up was ens3:1 ens3:2 . Don't use Zero it'll throw and error.

**Comment by Octolus** [comment]
@Lozy how would I use the multi ipaddr system?

I want the connecting ip to be the outbound one, i have multiple IP's.

**Comment by Lozy** [comment]
@Octolus Just installing danted following my script with args `--ip=a.a.a.a;b.b.b.b`
