### ISSUE TITLE
After clean install can't connect

### ISSUE THREAD

**Issue by swiftaes** [Lozy/danted#26]
After following your instructions and steps to install it it seems to be fine and work well but i cannot connect to the proxy i make, I've also tried adding a different user and still the same all ports are open etc so I have no idea what could cause this and I am quite in need of being able to setup a socks5. 

My OS CentOS 7 64bit

**Comment by Lozy** [comment]
Hi, please check the log 

> tail -f /var/log/sockd.log

Before that, test the library `pam_pwdfile.so`. Most of CentOS auth error because of the missing of this file.

> /lib64/security/pam_pwdfile.so

**Comment by swiftaes** [comment]
I've checked my logs and its clean just shows when I started and closed the sockd server. https://i.imgur.com/puuWfHG.png

As for the second part I have the pam_pwdile.so but I still seem to be unable to connect.

**Comment by Lozy** [comment]
There are some tips about debug

1. enable debug mode
     $ echo 'debug: 1' >> /etc/danted/sockd.conf
2. restart service 
     $ service sockd restart
3. check firewall in your pc console
    > telnet YourServerIPAddr Port 
    It should be conntected, or something wrong with your server's firewall setting.

4. do some socks5 request and tail the log
    $ tail -f /var/log/sockd.log

**Comment by swiftaes** [comment]
So i've enable debug mode and it still just showing me the same thing, I did try using curl to use the socks5 and give me the ip of the proxy through a different server and it worked but why am I not able to connect to it through a browser or applications?

**Comment by Lozy** [comment]
From your screenshot, the socks5 server runs fine.

Most of the browser like chrome or Firefox are not supporting socks5 with password auth.  I do suggest you disable password auth(pam) , using ip whitelist or using iptables to reach that.

**Comment by Lozy** [comment]
Disable pam auth.

```
pass {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        protocol: tcp udp
        method: none  # replace pam here
        log: connect disconnect
}
```

Without password protection, your socks5 proxy will be public. 
Do remember using iptables to limit that.

**Comment by swiftaes** [comment]
Ok thanks very much for that, now I know this is asking a bit much but would you be able to help me. I am not sure how to only allow a certain ip address with iptables for the proxy.

**Comment by Lozy** [comment]
2 ways to reach that.

1. filiter by iptables

```
iptables -A INPUT -s xxxx/32 -p tcp -m tcp --dport xxx -j ACCEPT # adding allow lan
iptables -A INPUT -p tcp -m tcp --dport xxx -j DROP # Drop other traffic
```

2. filiter by dante

```
pass {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        protocol: tcp udp
        method: pam # default method is pam
        log: connect disconnect
}

pass {
        from: xxxx/32 to: 0.0.0.0/0  # your ip lan
        protocol: tcp udp
        method: none
}
```
