### ISSUE TITLE
Dante server intall fail

### ISSUE THREAD

**Issue by twj2003** [Lozy/danted#27]
Centos 6 x64
Debian 7,and Debian 8
all got same issue on vultr vps

**Comment by twj2003** [comment]
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
Archive:  libpam-pwdfile.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of libpam-pwdfile.zip or
        libpam-pwdfile.zip.zip, and cannot find libpam-pwdfile.zip.ZIP, period.
bash: line 258: cd: libpam-pwdfile-master: No such file or directory
make: *** No targets specified and no makefile found.  Stop.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
bash: line 274: cd: dante-1.3.2.tar.gz: Not a directory
make: *** No targets specified and no makefile found.  Stop.
update-rc.d: using dependency based boot sequencing
insserv: warning: script 'sockd' missing LSB tags and overrides
 Dante Server Install Failed!

**Comment by Lozy** [comment]
Hi, i have fixed this issue because of dns server failed.

Please retry later.
