### ISSUE TITLE
not work :(

### ISSUE THREAD

**Issue by webapteka** [Lozy/danted#28]
Hello!

CentOS 7

My config file:

```
# Generate by sockd.info
# Generate interface 80.211.*.*
internal: 80.211.*.*  port = 2016
external: 80.211.*.*

method: pam none
clientmethod: none
user.privileged: root
user.notprivileged: sockd
logoutput: /var/log/sockd.log

client pass {
        from: 0.0.0.0/0  to: 0.0.0.0/0
}
client block {
        from: 0.0.0.0/0 to: 0.0.0.0/0
}
pass {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        protocol: tcp udp
        method: none
        log: connect disconnect
}

```

**In Firefox: The proxy server is refusing connections**

**Comment by Lozy** [comment]
1. First of all, check your firewall and make sure port of 2016 is open: iptables -L -n 

2. change config `method: pam none` to `method: none`
3. add new config `debug: 1` 
4. check the log '/var/log/sockd.log'

**Comment by mkfcga** [comment]
hi
i have client connection problem and
i got this error after set debug to 1

 recv_negotiate(): recvmsg() from mother returned -1 after having received 1 packets, errno = 11 (Resource temporarily unavailable)

**Comment by Lozy** [comment]
> hi
> i have client connection problem and
> i got this error after set debug to 1
> 
> recv_negotiate(): recvmsg() from mother returned -1 after having received 1 packets, errno = 11 (Resource temporarily unavailable)

Please check the `/etc/security/limits.conf`
