### ISSUE TITLE
https://public.sockd.info/ not working/downloading

### ISSUE THREAD

**Issue by pickleman111** [Lozy/danted#29]
site is failing

do u have a backup for all the required files?

**Comment by Lozy** [comment]
Hi, sorry for this issue.

Could you mind set a host record temporarily  `64.15.185.53  public.sockd.info` in `/etc/hosts`.

It will be fix when the domian's dns server recover.

**Comment by pickleman111** [comment]
thank you its working

btw one question,
 do u have a way to authorize socks5 acc/pass
by dynamicly linked through  mysql database

so i can make a webpage to edit pass in realtime

**Comment by pickleman111** [comment]
?

**Comment by Lozy** [comment]
sorry for delay.

As far as I know, you can't directly using mysql for dante auth.

However, you can modify pam auth_file (`/etc/danted/sockd.passwd`) to reached that.

**Comment by pickleman111** [comment]
anyway to modify that files dynamically through a database or outside webpage?
if u got skype/qq. we can talk about a paying feature

thanks

**Comment by Lozy** [comment]
Just write a rpc demo for this in python, you can use mysql database instead.

https://github.com/Lozy/HtpasswdRPC/blob/master/program.py
