### ISSUE TITLE
Danted Server [ PID.LOST;Unable ] 

### ISSUE THREAD

**Issue by 23330** [Lozy/danted#30]
myos:ubuntu 14.04 64位
root@ubuntu:~# service sockd restart
Restarting Dante SOCKS 5 daemon: 
Danted Server [ PID.LOST;Unable ] 
Danted Server [ Running ] 

cat log

Oct 22 22:09:55 (1508681395.999751) sockd[26102]: alert: sockdexit(): terminating
Oct 22 22:10:35 (1508681435.363699) sockd[26176]: info: dante/server[1] v1.3.2 running
Oct 22 22:11:04 (1508681464.872901) sockd[26176]: info: sigterm(): exiting on signal 15
Oct 22 22:11:04 (1508681464.872950) sockd[26176]: alert: sockdexit(): terminating
Oct 22 22:13:26 (1508681606.337942) sockd[26478]: info: dante/server[1] v1.3.2 running
Oct 22 22:14:38 (1508681678.258757) sockd[26478]: info: sigterm(): exiting on signal 15
Oct 22 22:14:38 (1508681678.258805) sockd[26478]: alert: sockdexit(): terminating
Oct 22 22:17:02 (1508681822.855205) sockd[26858]: info: dante/server[1] v1.3.2 running

my install method:
wget --no-check-certificate https://raw.github.com/Lozy/danted/master/install.sh -O install.sh 
bash install.sh --port=xx --user=xx --passwd=xx

Restarting Dante SOCKS 5 daemon: 
Danted Server [ PID.LOST;Unable ] 
Danted Server [ Start Failed ] 
 Dante Server Install Failed!

then i edit /etc/danted/sockd.conf

internal: myip port = xxx
external: eth0

then
service sockd start
Restarting Dante SOCKS 5 daemon: 
Danted Server [ PID.LOST;Unable ] 
Danted Server [ Running ] 

in fact socks5 work ok just start note:Danted Server [ PID.LOST;Unable ] what main?

**Comment by Lozy** [comment]
1. check process is online: `ps -ef | grep sockd`.  No output means offline.
2. check config `sockd -V`. No output is fine.

**Comment by 23330** [comment]
root@ubuntu:~# ps -ef | grep sockd
sockd    27577     1  0 22:25 ?        00:00:00 /etc/danted/sbin/sockd -f /etc/danted/sockd.conf -D -p /var/run/sockd.pid -N 1 -n
sockd    27578 27577  0 22:25 ?        00:00:00 sockd: negotiator: 0/24                                                          
sockd    27579 27577  0 22:25 ?        00:00:00 sockd: requestcompleter: 0/1                                                     
sockd    27580 27577  0 22:25 ?        00:00:00 sockd: requestcompleter: 0/1                                                     
sockd    27581 27577  0 22:25 ?        00:00:00 sockd: requestcompleter: 0/1                                                     
sockd    27582 27577  0 22:25 ?        00:00:00 sockd: requestcompleter: 0/1                                                     
sockd    27583 27577  0 22:25 ?        00:00:00 sockd: iorelayer: 1/8                                                            
sockd    27643 27577  0 22:26 ?        00:00:00 sockd: requestcompleter: 0/1                                                     
sockd    28163 27577  0 22:33 ?        00:00:00 sockd: iorelayer: 0/8                                                            
root     29378 29364  0 22:48 pts/0    00:00:00 grep --color=auto sockd
root@ubuntu:~# sockd -V
root@ubuntu:~#

**Comment by Lozy** [comment]
It works~ 

Can you connect the socks5 server? Don't mind the error `PID.LOST`.

**Comment by 23330** [comment]
emmm~~ ok  socks5 connect correct
