### ISSUE TITLE
Error autmethod

### ISSUE THREAD

**Issue by ajayucito** [Lozy/danted#31]
If I put:

method: username
clientmethod: username

Cant start sockd.

**Comment by Lozy** [comment]
Run
> /etc/danted/sbin/sockd -V

to check error.

**Comment by ajayucito** [comment]
I fixed the problem by modifying the install_centos.sh script on line 6 by:

VERSION = "1.4.2"

And I also modified line 73 by:

socksmethod: username

And line 119 by:

socksmethod: username

Then the service works with the latest version of Dante and correctly.
