### ISSUE TITLE
centos 6/7 fail

### ISSUE THREAD

**Issue by pickleman111** [Lozy/danted#35]
tried both 
all throw same error 

line 281 ./configure has no permission

so i add bash infront.
then i get error 
checking whether the C compiler works... configure: error: cannot run C compiled programs.

they are all newly installed centos. im able to get this to work in ubuntu, but never in centos

help

**Comment by pickleman111** [comment]
Configuring Dante 1.3.2:
checking for a BSD-compatible install... /usr/bin/install -c
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for style of include used by make... GNU
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details.
make: *** No targets specified and no makefile found.  Stop.
 Dante Server Install Failed!

**Comment by Chronicwtf** [comment]
I intalled this on gcloud and got the same error

**Comment by Lozy** [comment]
try add parameter when running compile

`./configure --host=arm`

**Comment by mojehb** [comment]
I have same problem in centos 7 
`bash: line 284: ./configure: Permission denied
make: *** No targets specified and no makefile found.  Stop.
 Dante Server Install Failed!`
What exactly should I do?
