### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by ghost** [Lozy/danted#37]
![image](https://user-images.githubusercontent.com/30369022/36193942-c401e8e0-11a2-11e8-9b2e-9078c96d02ac.png)
google cloud centos7

**Comment by Lozy** [comment]
Hi， 

Could you run 

> /etc/danted/sbin/sockd -f /etc/danted/sockd.conf

And paste the output here?

**Comment by ductai230894** [comment]
I have same problem
I try run above command, but don't see anything
Can't anybody fix this

**Comment by Lozy** [comment]
check `/etc/danted/sockd.conf` to make sure you have configured ip address
