### ISSUE TITLE
安装好了但是不能使用

### ISSUE THREAD

**Issue by nzcool** [Lozy/danted#38]
防火墙也关闭了，安装也正常。就是不能连接正常使用。telnet端口也正常。有人说是被墙了但是安装ssr可以正常使用。不知道什么原因。

**Comment by nzcool** [comment]
hentication service cannot retrieve authentication info
Feb 17 10:27:30 (1518863250.538161) sockd[21199]: info: block(1): tcp/connect ]: 42.200.212.129.45806 172.105.240.223.2018 -> 172.105.240.223.45806 149.154.175.50.443: pam_authenticate(): Authentication service cannot retrieve authentication info

**Comment by Lozy** [comment]
> Authentication service cannot retrieve authentication info

请关闭认证。 或者使用支持 socks5 认证的软件， 例如 Proxifier

> \# vi /etc/danted/sockd.conf

> pass {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        protocol: tcp udp
        method: none
        log: connect disconnect
}
