### ISSUE TITLE
阿里云国际版Ubuntu16.04安装后不管用

### ISSUE THREAD

**Issue by q465427587** [Lozy/danted#39]
已经解决 谢谢！

**Comment by q465427587** [comment]
安装后是阿里云国际版内网ip- - 无法设置公网的

**Comment by Lozy** [comment]
Hi, 有几个地方需要确认

1. 确认配置文件是否带上了 Ip 与端口  /etc/danted/sockd.conf

2. 确认是否正常启动 service sockd status

3. 确认 Iptables 以及 阿里云的 防火墙是否打开配置的端口.

阿里云国际版内网ip 与外网是1:1 绑定的, 配置为内网Ip 即可.

**Comment by q465427587** [comment]
你好。
我默认安装后显示绿色字体Dante Server Install Successfuly! ，修改/etc/danted/sockd.conf 内的内网ip为公网
通过service sockd state 查询 显示stop 。

**Comment by Lozy** [comment]
请修改/etc/danted/sockd.conf 内的IP 为机器内网的IP！ 然后重启服务

如果无法访问， 请查看 阿里云防火墙是否开放端口。

**Comment by q465427587** [comment]
端口默认全开的了- - 要不，tg上联系 我给你个机器您测试下- -

**Comment by q465427587** [comment]
Dante Server [ Stop ] 
不管修改不修改 重启后头提示stop

**Comment by Lozy** [comment]
@q465427587 发邮件给我 konianet@gmail.com 吧， 我看一下

**Comment by lancer-wang** [comment]
甲骨文,ubtntu20,遇到同样问题,只能为内网ip,端口全开,无法使用
![image](https://user-images.githubusercontent.com/69783837/141264171-4726644e-231c-495e-98e6-b93b6afc5ca1.png)


> 请修改/etc/danted/sockd.conf 内的IP 为机器内网的IP！ 然后重启服务
> 
> 如果无法访问， 请查看 阿里云防火墙是否开放端口。

**Comment by lancer-wang** [comment]
> 甲骨文,ubtntu20,遇到同样问题,只能为内网ip,端口全开,无法使用 ![image](https://user-images.githubusercontent.com/69783837/141264171-4726644e-231c-495e-98e6-b93b6afc5ca1.png)
> 
> > 请修改/etc/danted/sockd.conf 内的IP 为机器内网的IP！ 然后重启服务
> > 如果无法访问， 请查看 阿里云防火墙是否开放端口。

找到问题了,之前脑抽装过宝塔,后面虽然卸载了,但是防火墙居然还在
