### ISSUE TITLE
User not known to the underlying authentication module

### ISSUE THREAD

**Issue by Octolus** [Lozy/danted#42]
Getting this: User not known to the underlying authentication module

using "/etc/init.d/sockd status" lists the user fine, been reinstalling multiple times and reinstalling even the server.. Debian 8, vultr.

**Comment by Lozy** [comment]
Do you  try with 

> curl ifconfig.co --socks5 xxxx:xx  --proxy-user xx:xx

How do you get 'User not known to the underlying authentication module'?
