### ISSUE TITLE
Telegram calls not working

### ISSUE THREAD

**Issue by antue** [Lozy/danted#44]
Same as here https://stackoverflow.com/questions/49855516/telegram-calls-via-dante-socks5-proxy-server-not-working but with @Lozy  install.sh script for 1.3.2

Here is some log with udp/udpassociate action

`
`Apr 19 16:17:33 (1524143853.147297) sockd[22468]: info: pass(1): tcp/connect ]: 258 -> pam%tg@MYIP.55570 192.168.1.30.10800 -> 443, 443 -> 192.168.1.30.55570 149.154.167.51.5222 -> 258: local client closed.  Session duration: 11s
Apr 19 16:17:36 (1524143856.086742) sockd[22464]: info: pass(1): udp/udpassociate [: pam%tg@0.0.0.0.0 192.168.1.30.58761 -> 192.168.1.30.42546 0.0.0.0.0
Apr 19 16:17:38 (1524143858.388098) sockd[22468]: info: pass(1): tcp/connect ]: 687 -> pam%tg@MYIP.55569 192.168.1.30.10800 -> 1128, 1128 -> 192.168.1.30.55569 149.154.167.51.80 -> 687: local client closed.  Session duration: 16s
Apr 19 16:18:05 (1524143885.074179) sockd[22468]: info: pass(1): udp/udpassociate ]: 0/0 -> pam%tg@0.0.0.0.0 192.168.1.30.58761 -> 0/0, 0/0 -> 192.168.1.30.42546 0.0.0.0.0 -> 0/0: local client closed.  Session duration: 29s`

**Comment by h47e** [comment]
# Allow clients' voice traffic
socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    command: udpreply
    log: connect disconnect error
    socksmethod: username
}
iptables -A INPUT -p udp -m multiport --dports 1024:65535 -j ACCEPT
