### ISSUE TITLE
Install failed Debian-9 - x86_64

### ISSUE THREAD

**Issue by gooddaytoday** [Lozy/danted#45]
dante-1.3.2/example/sockd.conf
dante-1.3.2/example/sockd-basic.conf
dante-1.3.2/example/socks-simple-withoutnameserver.conf
dante-1.3.2/example/sockd-chaining.conf
dante-1.3.2/doc/Makefile.am
dante-1.3.2/doc/Makefile.in
dante-1.3.2/doc/sockd.8
dante-1.3.2/doc/sockd.conf.5
dante-1.3.2/doc/socks.conf.5
dante-1.3.2/doc/socksify.1
dante-1.3.2/doc/rfc1928.txt
dante-1.3.2/doc/rfc1929.txt
dante-1.3.2/doc/rfc1961.txt
dante-1.3.2/doc/SOCKS4.protocol
dante-1.3.2/doc/SOCKS4A.protocol
dante-1.3.2/doc/README.socksify
dante-1.3.2/doc/README.survey
dante-1.3.2/doc/README.usage
dante-1.3.2/bin/Makefile.am
dante-1.3.2/bin/Makefile.in
dante-1.3.2/bin/socksify.in
dante-1.3.2/SPECS/Makefile.am
dante-1.3.2/SPECS/Makefile.in
dante-1.3.2/SPECS/dante.spec.in
dante-1.3.2/SPECS/dante.spec
dante-1.3.2/capi/socks.h
dante-1.3.2/capi/socks_glibc.h
dante-1.3.2/capi/Makefile.am
dante-1.3.2/capi/Makefile.in
dante-1.3.2/capi/socks.h.in
dante-1.3.2/contrib/README
dante-1.3.2/contrib/Makefile.am
dante-1.3.2/contrib/Makefile.in
dante-1.3.2/contrib/sockd-stat.awk
dante-1.3.2/contrib/StartupItems.Dante
dante-1.3.2/contrib/StartupParameters.plist
dante-1.3.2/dlib64/Makefile.am
dante-1.3.2/dlib64/Makefile.in
bash: line 274: cd: too many arguments
make: *** No targets specified and no makefile found.  Stop.
Synchronizing state of sockd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable sockd

 Dante Server Install Failed!

**Comment by bobwang3** [comment]
同上

**Comment by Lozy** [comment]
Fix!

**Comment by MmrDev** [comment]
i have the same problem 
could you you help ?
