### ISSUE TITLE
I can't delete user

### ISSUE THREAD

**Issue by denisemenov** [Lozy/danted#46]
```
[root@test ~]# service sockd deluser test
Clearing User For Dante SOCKS 5 daemon:
/etc/init.d/sockd: line 212: del_user: command not found
[root@test ~]#
```

Centos 7

**Comment by alipour66m** [comment]
I have same issue on ubuntu 14.04

**Comment by m3g0byt3** [comment]
There is a typo in

**Comment by m3g0byt3** [comment]
There is a small typo in the init script, it can be fixed with following command:

`sudo sed -i 's/del_uer/del_user/g' /etc/init.d/sockd`

**Comment by denisemenov** [comment]
It was fixed earlier - https://github.com/Lozy/danted/commit/28514dd5c3a7ee5d99ec0dff4cc1b633f281989e
