### ISSUE TITLE
connection to the proxy server was closed unexpectedly

### ISSUE THREAD

**Issue by alipour66m** [Lozy/danted#48]
I installed danted script on Ubuntu 16.04 successfully.
In proxifer : 

[01:59] Testing Started.
	Proxy Server
	Address:	95.216.149.**:2016
	Protocol:	SOCKS 5
	Authentication: YES

[01:59] Starting: Test 1: Connection to the Proxy Server
[01:59] IP Address: 95.216.149.**
[01:59] Connection established
[01:59] Test passed.
[01:59] Starting: Test 2: Connection through the Proxy Server
[02:30] Error : connection to the proxy server was closed unexpectedly.
[02:30] Test failed.
[02:30] Testing Finished.

How can i fixed it?

this is my sockd.conf

internal: 95.216.149.**  port = 2016
external: 95.216.149.**

method: pam none
clientmethod: none
user.privileged: root
user.notprivileged: sockd
logoutput: /var/log/sockd.log

client pass {
        from: 0.0.0.0/0  to: 0.0.0.0/0
}
client block {
        from: 0.0.0.0/0 to: 0.0.0.0/0
}
pass {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        protocol: tcp udp
        method: pam
        log: connect disconnect
}
block {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        log: connect error
}

**Comment by Lozy** [comment]
- you should add user to suit `method: pam`

**Comment by mkfcga** [comment]
i have same problem and every thing is fine and green! 
socked runing fine! 
port is open.
firewall is down
using adduser to add users
"you should add user to suit method: pam"
can u explain more ?
