### ISSUE TITLE
debian7 x64位无法安装

### ISSUE THREAD

**Issue by lovesmean** [Lozy/danted#5]
Restarting Dante SOCKS daemon: 
 Danted Server [ PID.LOST;Unable ] 
cat: /var/run/sockd.pid: No such file or directory
 Danted Server [ Stop Done ] 
 Danted Server [ Start Faild ] 
 Dante Server Install Failed!

**Comment by Lozy** [comment]
可否提供更多的信息。或者私聊我帮你debug

**Comment by starrkdevil** [comment]
恩，我也遇到了同样的问题

**Comment by starrkdevil** [comment]
Ubuntu 14.04 64位

**Comment by Lozy** [comment]
bash -x install.sh 

看下在哪里异常~

**Comment by Bengiii** [comment]
我centos 7 也碰到这个问题

**Comment by Lozy** [comment]
麻烦各位下载新版本
