### ISSUE TITLE
关于玩绝地求生的问题

### ISSUE THREAD

**Issue by nzcool** [Lozy/danted#51]
在阿里云上架设成功，用tg测试也没问题。就是在玩绝地求生的时候卡在匹配界面，进不去。udp测试也没啥问题啊！难道还要设置哪里才行？

**Comment by nzcool** [comment]
哦对了，我用proxycap代理了nattypetester后测试为udpblocked

**Comment by nzcool** [comment]
网易UU太垃圾了，不考虑

**Comment by Lozy** [comment]
用ss吧~ 这个socks5 是原版不加密的, 不适合国内的网络环境.

**Comment by yunfengwangluo** [comment]
不知道可否支持 ipv6 地址 测试了一下 提示 安装失败了 或者 什么时候可以更新
