### ISSUE TITLE
Dante Server Install Failed in Debian 4.9.110-1 (2018-07-05) x86_64

### ISSUE THREAD

**Issue by NeoZion** [Lozy/danted#52]
Aug  5 00:36:26 instance-1 systemd[1]: Starting SOCKS (v4 and v5) proxy daemon (danted)...
Aug  5 00:36:26 instance-1 danted[3160]: Aug  5 00:36:26 (1533429386.294687) danted[3160]: warning: checkconfig(): no socks authentication methods enabled.  This means all socks requests will be blocked after negotiation.  Perhaps this is not intended?
Aug  5 00:36:26 instance-1 danted[3160]: Aug  5 00:36:26 (1533429386.298646) danted[3160]: error: checkconfig(): no internal address given for server to listen for clients on
Aug  5 00:36:26 instance-1 danted[3160]: Aug  5 00:36:26 (1533429386.299107) danted[3160]: alert: mother[1/1]: shutting down
Aug  5 00:36:26 instance-1 systemd[1]: danted.service: Control process exited, code=exited status=1
Aug  5 00:36:26 instance-1 systemd[1]: Failed to start SOCKS (v4 and v5) proxy daemon (danted).
Aug  5 00:36:26 instance-1 systemd[1]: danted.service: Unit entered failed state.
Aug  5 00:36:26 instance-1 systemd[1]: danted.service: Failed with result 'exit-code'.
Aug  5 00:36:26 instance-1 systemd[1]: Reloading.
Aug  5 00:36:26 instance-1 systemd[1]: apt-daily-upgrade.timer: Adding 9min 50.057080s random time.
Aug  5 00:36:57 instance-1 google-accounts: INFO Removing user ******
Aug  5 00:39:48 instance-1 systemd[1]: Starting SOCKS (v4 and v5) proxy daemon (danted)...
Aug  5 00:39:48 instance-1 danted[3248]: Aug  5 00:39:48 (1533429588.834814) danted[3248]: error: /etc/danted.conf: problem on line 1 near token "n": syntax error.  Please see the Dante manual for more information
Aug  5 00:39:48 instance-1 danted[3248]: Aug  5 00:39:48 (1533429588.837124) danted[3248]: alert: mother[1/1]: shutting down
Aug  5 00:39:48 instance-1 systemd[1]: danted.service: Control process exited, code=exited status=1
Aug  5 00:39:48 instance-1 systemd[1]: Failed to start SOCKS (v4 and v5) proxy daemon (dante
d).
Aug  5 00:39:48 instance-1 systemd[1]: danted.service: Unit entered failed state.
Aug  5 00:39:48 instance-1 systemd[1]: danted.service: Failed with result 'exit-code'.
Aug  5 00:40:11 instance-1 systemd[1]: Starting SOCKS (v4 and v5) proxy daemon (danted)...
Aug  5 00:40:11 instance-1 danted[3285]: Aug  5 00:40:11 (1533429611.873731) danted[3285]: e
rror: /etc/danted.conf: problem on line 1 near token "n": syntax error.  Please see the Dant
e manual for more information
Aug  5 00:40:11 instance-1 danted[3285]: Aug  5 00:40:11 (1533429611.874503) danted[3285]: a
lert: mother[1/1]: shutting down
Aug  5 00:40:11 instance-1 systemd[1]: danted.service: Control process exited, code=exited s
tatus=1
Aug  5 00:40:11 instance-1 systemd[1]: Failed to start SOCKS (v4 and v5) proxy daemon (dante
d).
Aug  5 00:40:11 instance-1 systemd[1]: danted.service: Unit entered failed state.
Aug  5 00:40:11 instance-1 systemd[1]: danted.service: Failed with result 'exit-code'.
Aug  5 00:52:33 instance-1 systemd[1]: Starting SOCKS (v4 and v5) proxy daemon (danted)...
Aug  5 00:52:33 instance-1 danted[3426]: Aug  5 00:52:33 (1533430353.745696) danted[3426]: e
rror: /etc/danted.conf: problem on line 1 near token "n": syntax error.  Please see the Dant
e manual for more information
Aug  5 00:52:33 instance-1 danted[3426]: Aug  5 00:52:33 (1533430353.747895) danted[3426]: a
lert: mother[1/1]: shutting down
 Dante Server Install Failed!

**Comment by Lozy** [comment]
Hi, please try to use `--ip` for virtual server

```
--ip="A.A.A.A:B.B.B.B"
```

**Comment by NeoZion** [comment]
Hi,I'm so sorry. It looks like a new problem.
For example
mv -f .deps/sockd_socket.Tpo .deps/sockd_socket.Po
gcc -DHAVE_CONFIG_H -I. -I../include -I../include -I../libscompat -I../lib  -D_XOPEN_SOURCE=600 -D_XOPEN_SOURCE_EXTENDED -D_BSD_SOURCE -U__GNUC__ -D__GNUC__=0 -DDEBUG=0 -DSOCKS_SERVER=
1 -DSOCKS_CLIENT=0 -DSOCKSLIBRARY_DYNAMIC=1 -g -O2  -pipe  -MT sockd_util.o -MD -MP -MF .deps/sockd_util.Tpo -c -o sockd_util.o sockd_util.c
In file included from /usr/include/x86_64-linux-gnu/sys/types.h:25:0,
                 from ../include/osdep.h:47,
                 from ../include/common.h:56,
                 from sockd_util.c:48:
/usr/include/features.h:148:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
mv -f .deps/sockd_util.Tpo .deps/sockd_util.Po
gcc -DHAVE_CONFIG_H -I. -I../include -I../include -I../libscompat -I../lib  -D_XOPEN_SOURCE=600 -D_XOPEN_SOURCE_EXTENDED -D_BSD_SOURCE -U__GNUC__ -D__GNUC__=0 -DDEBUG=0 -DSOCKS_SERVER=
1 -DSOCKS_CLIENT=0 -DSOCKSLIBRARY_DYNAMIC=1 -g -O2  -pipe  -MT interposition.o -MD -MP -MF .deps/interposition.Tpo -c -o interposition.o `test -f '../dlib/interposition.c' || echo './'
`../dlib/interposition.c
In file included from /usr/include/x86_64-linux-gnu/sys/types.h:25:0,
                 from ../include/osdep.h:47,
                 from ../include/common.h:56,
                 from ../dlib/interposition.c:46:
/usr/include/features.h:148:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
mv -f .deps/interposition.Tpo .deps/interposition.Po
/bin/bash ../libtool --tag=CC   --mode=link gcc -DSOCKS_SERVER=1 -DSOCKS_CLIENT=0 -DSOCKSLIBRARY_DYNAMIC=1 -g -O2  -pipe    -o sockd addressmatch.o authneg.o broken.o clientprotocol.o 
config.o config_parse.o config_scan.o debug.o gssapi.o hostcache.o httpproxy.o io.o iobuf.o log.o protocol.o serr.o socket.o tostring.o udp_util.o upnp.o userio.o util.o accesscheck.o 
auth_bsd.o auth_pam.o auth_password.o bandwidth.o bandwidth_key.o checkmodule.o getoutaddr.o iface.o ldap.o ldap_util.o method.o method_gssapi.o method_uname.o privileges.o redirect.o 
redirect_key.o rule.o serverconfig.o session.o session_key.o shmem.o sockd.o sockd_child.o sockd_io.o sockd_negotiate.o sockd_protocol.o sockd_request.o sockd_socket.o sockd_util.o int
erposition.o  ../libscompat/libscompat.la -lwrap  -lpam -lnsl -lcrypt  -ldl 
mkdir .libs
gcc -DSOCKS_SERVER=1 -DSOCKS_CLIENT=0 -DSOCKSLIBRARY_DYNAMIC=1 -g -O2 -pipe -o sockd addressmatch.o authneg.o broken.o clientprotocol.o config.o config_parse.o config_scan.o debug.o gs
sapi.o hostcache.o httpproxy.o io.o iobuf.o log.o protocol.o serr.o socket.o tostring.o udp_util.o upnp.o userio.o util.o accesscheck.o auth_bsd.o auth_pam.o auth_password.o bandwidth.
o bandwidth_key.o checkmodule.o getoutaddr.o iface.o ldap.o ldap_util.o method.o method_gssapi.o method_uname.o privileges.o redirect.o redirect_key.o rule.o serverconfig.o session.o s
ession_key.o shmem.o sockd.o sockd_child.o sockd_io.o sockd_negotiate.o sockd_protocol.o sockd_request.o sockd_socket.o sockd_util.o interposition.o  ../libscompat/.libs/libscompat.a -
lwrap -lpam -lnsl -lcrypt -ldl  
make[1]: Leaving directory '/home/*****/dante-1.3.2/sockd'
Making all in unlicensed
make[1]: Entering directory '/home/*****/dante-1.3.2/unlicensed'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/*****/dante-1.3.2/unlicensed'
Making all in example
make[1]: Entering directory '/home/*****/dante-1.3.2/example'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/*****/dante-1.3.2/example'
Making all in doc
make[1]: Entering directory '/home/*****/dante-1.3.2/doc'
bash: line 305: service: command not found
 Dante Server Install Failed! 
bash: line 331: /etc/init.d/sockd: No such file or directory

**Comment by Lozy** [comment]
Hi, It looks really like a environment issue.

Could you mind send me (konianet#gmail.com) the Ip and login info of this server?

**Comment by NeoZion** [comment]
I'm so sorry.But this is Google Cloud for Debian.
