### ISSUE TITLE
ubuntu 18.04.0 LTS安装失败

### ISSUE THREAD

**Issue by Mirasc** [Lozy/danted#55]
Current OS: Ubuntu 18.04.1 LTS
Current Options: 
Hit:1 http://mirrors.digitalocean.com/ubuntu bionic InRelease
Hit:2 http://mirrors.digitalocean.com/ubuntu bionic-updates InRelease                  
Hit:3 http://mirrors.digitalocean.com/ubuntu bionic-backports InRelease                
Hit:4 https://download.docker.com/linux/ubuntu bionic InRelease                        
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease                      
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libpam0g-dev' instead of 'libpam-dev'
g++ is already the newest version (4:7.3.0-3ubuntu2).
gcc is already the newest version (4:7.3.0-3ubuntu2).
libpam0g-dev is already the newest version (1.1.8-3.6ubuntu2).
libwrap0-dev is already the newest version (7.6.q-27).
make is already the newest version (4.1-9.1ubuntu1).
unzip is already the newest version (6.0-21ubuntu1).
apache2-utils is already the newest version (2.4.29-1ubuntu4.3).
The following package was automatically installed and is no longer required:
  grub-pc-bin
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
dante-1.3.2/README
dante-1.3.2/acinclude.m4
dante-1.3.2/preload.m4
dante-1.3.2/miniupnpc.m4
dante-1.3.2/gssapi.m4
dante-1.3.2/kerberos.m4
dante-1.3.2/ldap.m4
dante-1.3.2/sasl.m4
dante-1.3.2/libscompat.m4
dante-1.3.2/configure.ac
dante-1.3.2/aclocal.m4
dante-1.3.2/Makefile.am
dante-1.3.2/Makefile.in
dante-1.3.2/VERSION.in
dante-1.3.2/configure
dante-1.3.2/INSTALL
dante-1.3.2/NEWS
dante-1.3.2/config.guess
dante-1.3.2/config.sub
dante-1.3.2/depcomp
dante-1.3.2/install-sh
dante-1.3.2/ltmain.sh
dante-1.3.2/missing
dante-1.3.2/BUGS
dante-1.3.2/CREDITS
dante-1.3.2/LICENSE
dante-1.3.2/SUPPORT
dante-1.3.2/VERSION
dante-1.3.2/UPGRADE
dante-1.3.2/README.ldap
dante-1.3.2/include/common.h
dante-1.3.2/include/sockd.h
dante-1.3.2/include/socks.h
dante-1.3.2/include/config.h
dante-1.3.2/include/yacconfig.h
dante-1.3.2/include/redefac.h
dante-1.3.2/include/interposition.h
dante-1.3.2/include/tostring.h
dante-1.3.2/include/osdep.h
dante-1.3.2/include/upnp.h
dante-1.3.2/include/socks_gssapi.h
dante-1.3.2/include/symbols.h
dante-1.3.2/include/Makefile.am
dante-1.3.2/include/Makefile.in
dante-1.3.2/include/autoconf.h.in
dante-1.3.2/include/redefgen.sh
dante-1.3.2/include/symbols_common.txt
dante-1.3.2/include/symbols_freebsd.txt
dante-1.3.2/include/symbols_glibc.txt
dante-1.3.2/include/symbols_osol.txt
dante-1.3.2/include/symbols_osol_stdio.txt
dante-1.3.2/include/symbols_darwin.txt
dante-1.3.2/libscompat/daemon.h
dante-1.3.2/libscompat/difftime.h
dante-1.3.2/libscompat/ifaddrs_compat.h
dante-1.3.2/libscompat/sockatmark.h
dante-1.3.2/libscompat/strlcpy.h
dante-1.3.2/libscompat/timers.h
dante-1.3.2/libscompat/vis_compat.h
dante-1.3.2/libscompat/issetugid.h
dante-1.3.2/libscompat/Makefile.am
dante-1.3.2/libscompat/Makefile.in
dante-1.3.2/libscompat/difftime.c
dante-1.3.2/libscompat/daemon.c
dante-1.3.2/libscompat/hstrerror.c
dante-1.3.2/libscompat/inet_aton.c
dante-1.3.2/libscompat/inet_ntoa.c
dante-1.3.2/libscompat/inet_pton.c
dante-1.3.2/libscompat/issetugid.c
dante-1.3.2/libscompat/memmove.c
dante-1.3.2/libscompat/setproctitle.c
dante-1.3.2/libscompat/sockatmark.c
dante-1.3.2/libscompat/strlcpy.c
dante-1.3.2/libscompat/strvis.c
dante-1.3.2/libscompat/vsyslog.c
dante-1.3.2/libscompat/seteuid.c
dante-1.3.2/libscompat/getifaddrs.c
dante-1.3.2/lib/config_parse.h
dante-1.3.2/lib/Makefile.am
dante-1.3.2/lib/Makefile.in
dante-1.3.2/lib/config_parse.c
dante-1.3.2/lib/config_scan.c
dante-1.3.2/lib/Raccept.c
dante-1.3.2/lib/Rbind.c
dante-1.3.2/lib/Rgetpeername.c
dante-1.3.2/lib/Rgetsockname.c
dante-1.3.2/lib/Rgetsockopt.c
dante-1.3.2/lib/Rrresvport.c
dante-1.3.2/lib/io.c
dante-1.3.2/lib/address.c
dante-1.3.2/lib/authneg.c
dante-1.3.2/lib/client.c
dante-1.3.2/lib/clientconfig.c
dante-1.3.2/lib/clientprotocol.c
dante-1.3.2/lib/udp.c
dante-1.3.2/lib/userio.c
dante-1.3.2/lib/connectchild.c
dante-1.3.2/lib/config.c
dante-1.3.2/lib/log.c
dante-1.3.2/lib/protocol.c
dante-1.3.2/lib/socket.c
dante-1.3.2/lib/udp_util.c
dante-1.3.2/lib/util.c
dante-1.3.2/lib/Rbindresvport.c
dante-1.3.2/lib/Rconnect.c
dante-1.3.2/lib/Rgethostbyname.c
dante-1.3.2/lib/debug.c
dante-1.3.2/lib/Rcompat.c
dante-1.3.2/lib/hostcache.c
dante-1.3.2/lib/broken.c
dante-1.3.2/lib/serr.c
dante-1.3.2/lib/httpproxy.c
dante-1.3.2/lib/tostring.c
dante-1.3.2/lib/addressmatch.c
dante-1.3.2/lib/Rlisten.c
dante-1.3.2/lib/upnp.c
dante-1.3.2/lib/gssapi.c
dante-1.3.2/lib/iobuf.c
dante-1.3.2/lib/config_parse.y
dante-1.3.2/lib/config_scan.l
dante-1.3.2/dlib/Makefile.am
dante-1.3.2/dlib/Makefile.in
dante-1.3.2/dlib/interposition.c
dante-1.3.2/dlib/int_osf1.c
dante-1.3.2/dlib/int_osf2.c
dante-1.3.2/dlib/int_osf3.c
dante-1.3.2/sockd/Makefile.am
dante-1.3.2/sockd/Makefile.in
dante-1.3.2/sockd/accesscheck.c
dante-1.3.2/sockd/auth_bsd.c
dante-1.3.2/sockd/auth_pam.c
dante-1.3.2/sockd/auth_password.c
dante-1.3.2/sockd/bandwidth.c
dante-1.3.2/sockd/bandwidth_key.c
dante-1.3.2/sockd/checkmodule.c
dante-1.3.2/sockd/getoutaddr.c
dante-1.3.2/sockd/iface.c
dante-1.3.2/sockd/ldap.c
dante-1.3.2/sockd/ldap_util.c
dante-1.3.2/sockd/method.c
dante-1.3.2/sockd/method_gssapi.c
dante-1.3.2/sockd/method_uname.c
dante-1.3.2/sockd/privileges.c
dante-1.3.2/sockd/redirect.c
dante-1.3.2/sockd/redirect_key.c
dante-1.3.2/sockd/rule.c
dante-1.3.2/sockd/serverconfig.c
dante-1.3.2/sockd/session.c
dante-1.3.2/sockd/shmem.c
dante-1.3.2/sockd/session_key.c
dante-1.3.2/sockd/sockd.c
dante-1.3.2/sockd/sockd_child.c
dante-1.3.2/sockd/sockd_io.c
dante-1.3.2/sockd/sockd_negotiate.c
dante-1.3.2/sockd/sockd_protocol.c
dante-1.3.2/sockd/sockd_request.c
dante-1.3.2/sockd/sockd_socket.c
dante-1.3.2/sockd/sockd_util.c
dante-1.3.2/unlicensed/Makefile.am
dante-1.3.2/unlicensed/Makefile.in
dante-1.3.2/unlicensed/checkmodule.c
dante-1.3.2/unlicensed/bandwidth.c
dante-1.3.2/unlicensed/bandwidth_key.c
dante-1.3.2/unlicensed/redirect.c
dante-1.3.2/unlicensed/redirect_key.c
dante-1.3.2/unlicensed/session.c
dante-1.3.2/unlicensed/session_key.c
dante-1.3.2/unlicensed/ldap.c
dante-1.3.2/unlicensed/ldap_key.c
dante-1.3.2/example/Makefile.am
dante-1.3.2/example/Makefile.in
dante-1.3.2/example/socks-simple.conf
dante-1.3.2/example/socks.conf
dante-1.3.2/example/sockd.conf
dante-1.3.2/example/sockd-basic.conf
dante-1.3.2/example/socks-simple-withoutnameserver.conf
dante-1.3.2/example/sockd-chaining.conf
dante-1.3.2/doc/Makefile.am
dante-1.3.2/doc/Makefile.in
dante-1.3.2/doc/sockd.8
dante-1.3.2/doc/sockd.conf.5
dante-1.3.2/doc/socks.conf.5
dante-1.3.2/doc/socksify.1
dante-1.3.2/doc/rfc1928.txt
dante-1.3.2/doc/rfc1929.txt
dante-1.3.2/doc/rfc1961.txt
dante-1.3.2/doc/SOCKS4.protocol
dante-1.3.2/doc/SOCKS4A.protocol
dante-1.3.2/doc/README.socksify
dante-1.3.2/doc/README.survey
dante-1.3.2/doc/README.usage
dante-1.3.2/bin/Makefile.am
dante-1.3.2/bin/Makefile.in
dante-1.3.2/bin/socksify.in
dante-1.3.2/SPECS/Makefile.am
dante-1.3.2/SPECS/Makefile.in
dante-1.3.2/SPECS/dante.spec.in
dante-1.3.2/SPECS/dante.spec
dante-1.3.2/capi/socks.h
dante-1.3.2/capi/socks_glibc.h
dante-1.3.2/capi/Makefile.am
dante-1.3.2/capi/Makefile.in
dante-1.3.2/capi/socks.h.in
dante-1.3.2/contrib/README
dante-1.3.2/contrib/Makefile.am
dante-1.3.2/contrib/Makefile.in
dante-1.3.2/contrib/sockd-stat.awk
dante-1.3.2/contrib/StartupItems.Dante
dante-1.3.2/contrib/StartupParameters.plist
dante-1.3.2/dlib64/Makefile.am
dante-1.3.2/dlib64/Makefile.in
Configuring Dante 1.3.2:
checking for a BSD-compatible install... /usr/bin/install -c
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for style of include used by make... GNU
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ld used by gcc... /usr/bin/x86_64-linux-gnu-ld
checking if the linker (/usr/bin/x86_64-linux-gnu-ld) is GNU ld... yes
checking for /usr/bin/x86_64-linux-gnu-ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for g77... no
checking for xlf... no
checking for f77... no
checking for frt... no
checking for pgf77... no
checking for cf77... no
checking for fort77... no
checking for fl32... no
checking for af77... no
checking for xlf90... no
checking for f90... no
checking for pgf90... no
checking for pghpf... no
checking for epcf90... no
checking for gfortran... no
checking for g95... no
checking for xlf95... no
checking for f95... no
checking for fort... no
checking for ifort... no
checking for ifc... no
checking for efc... no
checking for pgf95... no
checking for lf95... no
checking for ftn... no
checking whether we are using the GNU Fortran 77 compiler... no
checking whether  accepts -g... no
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC
checking if gcc PIC flag -fPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking whether the gcc linker (/usr/bin/x86_64-linux-gnu-ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
configure: creating libtool
appending configuration tag "CXX" to libtool
checking for ld used by g++... /usr/bin/x86_64-linux-gnu-ld -m elf_x86_64
checking if the linker (/usr/bin/x86_64-linux-gnu-ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/x86_64-linux-gnu-ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC
checking if g++ PIC flag -fPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking whether the g++ linker (/usr/bin/x86_64-linux-gnu-ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
(cached) (cached) checking how to hardcode library paths into programs... immediate
appending configuration tag "F77" to libtool
checking how to run the C preprocessor... gcc -E
checking for compiler flags... none
checking for support for -pipe compiler flag... yes
checking for support for -Wbounded compiler flag... no
checking for compilation with debugging... checking for live debugging... no
checking for warning flags... none
checking for compliation with DIAGNOSTIC... no
checking for profiled compilation... no
checking whether libwrap should be disabled... no
checking for bison... no
checking for byacc... no
checking for gawk... (cached) gawk
checking for flex... no
checking for lex... no
checking for char... no
checking size of char... 0
checking for short... no
checking size of short... 0
checking for int... no
checking size of int... 0
checking for long... no
checking size of long... 0
checking for sys/wait.h that is POSIX.1 compatible... yes
checking fcntl.h usability... no
checking fcntl.h presence... yes
configure: WARNING: fcntl.h: present but cannot be compiled
configure: WARNING: fcntl.h:     check for missing prerequisite headers?
configure: WARNING: fcntl.h: see the Autoconf documentation
configure: WARNING: fcntl.h:     section "Present But Cannot Be Compiled"
configure: WARNING: fcntl.h: proceeding with the preprocessor's result
configure: WARNING: fcntl.h: in the future, the compiler will take precedence
checking for fcntl.h... yes
checking limits.h usability... no
checking limits.h presence... yes
configure: WARNING: limits.h: present but cannot be compiled
configure: WARNING: limits.h:     check for missing prerequisite headers?
configure: WARNING: limits.h: see the Autoconf documentation
configure: WARNING: limits.h:     section "Present But Cannot Be Compiled"
configure: WARNING: limits.h: proceeding with the preprocessor's result
configure: WARNING: limits.h: in the future, the compiler will take precedence
checking for limits.h... yes
checking malloc.h usability... no
checking malloc.h presence... yes
configure: WARNING: malloc.h: present but cannot be compiled
configure: WARNING: malloc.h:     check for missing prerequisite headers?
configure: WARNING: malloc.h: see the Autoconf documentation
configure: WARNING: malloc.h:     section "Present But Cannot Be Compiled"
configure: WARNING: malloc.h: proceeding with the preprocessor's result
configure: WARNING: malloc.h: in the future, the compiler will take precedence
checking for malloc.h... yes
checking paths.h usability... no
checking paths.h presence... yes
configure: WARNING: paths.h: present but cannot be compiled
configure: WARNING: paths.h:     check for missing prerequisite headers?
configure: WARNING: paths.h: see the Autoconf documentation
configure: WARNING: paths.h:     section "Present But Cannot Be Compiled"
configure: WARNING: paths.h: proceeding with the preprocessor's result
configure: WARNING: paths.h: in the future, the compiler will take precedence
checking for paths.h... yes
checking for strings.h... (cached) yes
checking syslog.h usability... no
checking syslog.h presence... yes
configure: WARNING: syslog.h: present but cannot be compiled
configure: WARNING: syslog.h:     check for missing prerequisite headers?
configure: WARNING: syslog.h: see the Autoconf documentation
configure: WARNING: syslog.h:     section "Present But Cannot Be Compiled"
configure: WARNING: syslog.h: proceeding with the preprocessor's result
configure: WARNING: syslog.h: in the future, the compiler will take precedence
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking crypt.h usability... no
checking crypt.h presence... yes
configure: WARNING: crypt.h: present but cannot be compiled
configure: WARNING: crypt.h:     check for missing prerequisite headers?
configure: WARNING: crypt.h: see the Autoconf documentation
configure: WARNING: crypt.h:     section "Present But Cannot Be Compiled"
configure: WARNING: crypt.h: proceeding with the preprocessor's result
configure: WARNING: crypt.h: in the future, the compiler will take precedence
checking for crypt.h... yes
checking sys/file.h usability... no
checking sys/file.h presence... yes
configure: WARNING: sys/file.h: present but cannot be compiled
configure: WARNING: sys/file.h:     check for missing prerequisite headers?
configure: WARNING: sys/file.h: see the Autoconf documentation
configure: WARNING: sys/file.h:     section "Present But Cannot Be Compiled"
configure: WARNING: sys/file.h: proceeding with the preprocessor's result
configure: WARNING: sys/file.h: in the future, the compiler will take precedence
checking for sys/file.h... yes
checking sys/ioctl.h usability... no
checking sys/ioctl.h presence... yes
configure: WARNING: sys/ioctl.h: present but cannot be compiled
configure: WARNING: sys/ioctl.h:     check for missing prerequisite headers?
configure: WARNING: sys/ioctl.h: see the Autoconf documentation
configure: WARNING: sys/ioctl.h:     section "Present But Cannot Be Compiled"
configure: WARNING: sys/ioctl.h: proceeding with the preprocessor's result
configure: WARNING: sys/ioctl.h: in the future, the compiler will take precedence
checking for sys/ioctl.h... yes
checking sys/time.h usability... no
checking sys/time.h presence... yes
configure: WARNING: sys/time.h: present but cannot be compiled
configure: WARNING: sys/time.h:     check for missing prerequisite headers?
configure: WARNING: sys/time.h: see the Autoconf documentation
configure: WARNING: sys/time.h:     section "Present But Cannot Be Compiled"
configure: WARNING: sys/time.h: proceeding with the preprocessor's result
configure: WARNING: sys/time.h: in the future, the compiler will take precedence
checking for sys/time.h... yes
checking tcpd.h usability... no
checking tcpd.h presence... yes
configure: WARNING: tcpd.h: present but cannot be compiled
configure: WARNING: tcpd.h:     check for missing prerequisite headers?
configure: WARNING: tcpd.h: see the Autoconf documentation
configure: WARNING: tcpd.h:     section "Present But Cannot Be Compiled"
configure: WARNING: tcpd.h: proceeding with the preprocessor's result
configure: WARNING: tcpd.h: in the future, the compiler will take precedence
checking for tcpd.h... yes
checking shadow.h usability... no
checking shadow.h presence... yes
configure: WARNING: shadow.h: present but cannot be compiled
configure: WARNING: shadow.h:     check for missing prerequisite headers?
configure: WARNING: shadow.h: see the Autoconf documentation
configure: WARNING: shadow.h:     section "Present But Cannot Be Compiled"
configure: WARNING: shadow.h: proceeding with the preprocessor's result
configure: WARNING: shadow.h: in the future, the compiler will take precedence
checking for shadow.h... yes
checking ifaddrs.h usability... no
checking ifaddrs.h presence... yes
configure: WARNING: ifaddrs.h: present but cannot be compiled
configure: WARNING: ifaddrs.h:     check for missing prerequisite headers?
configure: WARNING: ifaddrs.h: see the Autoconf documentation
configure: WARNING: ifaddrs.h:     section "Present But Cannot Be Compiled"
configure: WARNING: ifaddrs.h: proceeding with the preprocessor's result
configure: WARNING: ifaddrs.h: in the future, the compiler will take precedence
checking for ifaddrs.h... yes
checking sys/sem.h usability... no
checking sys/sem.h presence... yes
configure: WARNING: sys/sem.h: present but cannot be compiled
configure: WARNING: sys/sem.h:     check for missing prerequisite headers?
configure: WARNING: sys/sem.h: see the Autoconf documentation
configure: WARNING: sys/sem.h:     section "Present But Cannot Be Compiled"
configure: WARNING: sys/sem.h: proceeding with the preprocessor's result
configure: WARNING: sys/sem.h: in the future, the compiler will take precedence
checking for sys/sem.h... yes
checking netinet/in.h usability... no
checking netinet/in.h presence... yes
configure: WARNING: netinet/in.h: present but cannot be compiled
configure: WARNING: netinet/in.h:     check for missing prerequisite headers?
configure: WARNING: netinet/in.h: see the Autoconf documentation
configure: WARNING: netinet/in.h:     section "Present But Cannot Be Compiled"
configure: WARNING: netinet/in.h: proceeding with the preprocessor's result
configure: WARNING: netinet/in.h: in the future, the compiler will take precedence
checking for netinet/in.h... yes
checking sys/ipc.h usability... no
checking sys/ipc.h presence... yes
configure: WARNING: sys/ipc.h: present but cannot be compiled
configure: WARNING: sys/ipc.h:     check for missing prerequisite headers?
configure: WARNING: sys/ipc.h: see the Autoconf documentation
configure: WARNING: sys/ipc.h:     section "Present But Cannot Be Compiled"
configure: WARNING: sys/ipc.h: proceeding with the preprocessor's result
configure: WARNING: sys/ipc.h: in the future, the compiler will take precedence
checking for sys/ipc.h... yes
checking arpa/nameser.h usability... no
checking arpa/nameser.h presence... yes
configure: WARNING: arpa/nameser.h: present but cannot be compiled
configure: WARNING: arpa/nameser.h:     check for missing prerequisite headers?
configure: WARNING: arpa/nameser.h: see the Autoconf documentation
configure: WARNING: arpa/nameser.h:     section "Present But Cannot Be Compiled"
configure: WARNING: arpa/nameser.h: proceeding with the preprocessor's result
configure: WARNING: arpa/nameser.h: in the future, the compiler will take precedence
checking for arpa/nameser.h... yes
checking net/if_dl.h usability... no
checking net/if_dl.h presence... no
checking for net/if_dl.h... no
checking execinfo.h usability... no
checking execinfo.h presence... yes
configure: WARNING: execinfo.h: present but cannot be compiled
configure: WARNING: execinfo.h:     check for missing prerequisite headers?
configure: WARNING: execinfo.h: see the Autoconf documentation
configure: WARNING: execinfo.h:     section "Present But Cannot Be Compiled"
configure: WARNING: execinfo.h: proceeding with the preprocessor's result
configure: WARNING: execinfo.h: in the future, the compiler will take precedence
checking for execinfo.h... yes
checking sys/pstat.h usability... no
checking sys/pstat.h presence... no
checking for sys/pstat.h... no
checking for netinet/ip_var.h... no
checking for resolv.h... yes
checking for config file location... default
checking for sockd config file location... /etc/danted/sockd.conf
checking for pid file location... default
checking for SOCKD_IOMAX value... default
checking for SOCKD_NEGOTIATEMAX value... default
checking sys/sockio.h usability... no
checking sys/sockio.h presence... no
checking for sys/sockio.h... no
checking whether <sys/types.h> defines const... no
checking for an ANSI C-conforming const... yes
checking for supported routing socket communication... yes
checking whether <netdb.h> declares h_errno... yes
checking for struct ip_opts in <netinet/in.h>... no
checking whether <sys/types.h> defines inline... no
checking for inline... inline
checking for uid_t in sys/types.h... yes
checking for off_t... no
checking for pid_t... no
checking for size_t... no
checking whether time.h and sys/time.h may both be included... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... unknown
checking for _LARGE_FILES value needed for large files... unknown
checking for in6_addr... no
checking to see if openlog accepts LOG_PERROR... yes
checking to see if stdlib.h defines EXIT_FAILURE... yes
checking whether <sys/socket.h> uses AF_UNIX... no
checking for SIGINFO... no
checking to see if MSG_WAITALL exists... yes
checking whether realloc with a NULL pointer calls malloc... no
checking whether free can be called with NULL... no
checking for dlfcn.h... (cached) yes
checking whether all interposition usage should be disabled... no
checking whether interposition in the client should be disabled... no
checking whether interposition in the server should be disabled... no
checking to see if dlopen param has DL_ and not RTLD_ prefix... yes
checking for __fprintf_chk... yes
checking for __vfprintf_chk... yes
checking for _IO_getc... yes
checking for _IO_putc... yes
checking prototypes for accept... failure
checking prototypes for bind... failure
checking prototypes for connect... failure
checking prototypes for gethostbyaddr... failure
checking prototypes for getpeername... failure
checking prototypes for getsockname... failure
checking prototypes for getsockopt... failure
checking prototypes for listen... failure
checking prototypes for read... failure
checking prototypes for readv... failure
checking prototypes for recv... failure
checking prototypes for recvfrom... failure
checking prototypes for recvmsg... failure
checking prototypes for send... failure
checking prototypes for sendmsg... failure
checking prototypes for sendto... failure
checking prototypes for write... failure
checking prototypes for writev... failure
checking prototypes for getc... failure
checking prototypes for fgetc... failure
checking prototypes for gets... failure
checking prototypes for fgets... failure
checking prototypes for putc... failure
checking prototypes for fputc... failure
checking prototypes for puts... failure
checking prototypes for fputs... failure
checking prototypes for fflush... failure
checking prototypes for fclose... failure
checking prototypes for fprintf... failure
checking prototypes for vfprintf... failure
checking prototypes for printf... failure
checking prototypes for vprintf... failure
checking prototypes for fwrite... failure
checking prototypes for fread... failure
checking prototypes for _IO_getc... failure
checking prototypes for _IO_putc... failure

error: attempt to determine function prototypes failed,
       and will probably mean that building of libdsocks,
       which allows on-the-fly socksification of dynamic
       binaries, will not work.

       You have several options:

       1. If you do not need libdsocks, run configure with the
          option --disable-preload.
       2. Submit a bugreport.
       3. Find the prototypes used on your platform for the
          failed functions, and add them to the configure.ac
          file. Then use autoconf (which must be installed)
          to regenerate the configure script.
          Function prototype definitions can usually be found
          in the manual page for the function or in a system
          include file (usually located under /usr/include).
make: *** No targets specified and no makefile found.  Stop.
Synchronizing state of sockd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable sockd
 Dante Server Install Failed!

**Comment by lgg** [comment]
@Mirasc `bash install.sh -p` worked for me

**Comment by PirateVida** [comment]
> @Mirasc `bash install.sh -p` worked for me

This works for me as well!

**Comment by xsname** [comment]
root@cavpn:/home/hsn# bash install.sh -p
Current OS: Ubuntu 18.04.3 LTS
Current Options: -p
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libpam0g-dev' instead of 'libpam-dev'
libwrap0-dev is already the newest version (7.6.q-27).
make is already the newest version (4.1-9.1ubuntu1).
unzip is already the newest version (6.0-21ubuntu1).
apache2-utils is already the newest version (2.4.29-1ubuntu4.11).
g++ is already the newest version (4:7.4.0-1ubuntu2.3).
gcc is already the newest version (4:7.4.0-1ubuntu2.3).
libpam0g-dev is already the newest version (1.1.8-3.6ubuntu2.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Selecting previously unselected package dante.
(Reading database ... 72370 files and directories currently installed.)
Preparing to unpack dante_1.3.2-1_x86_64.deb ...
Unpacking dante (1.3.2-1) ...
Setting up dante (1.3.2-1) ...
Adding User For Dante SOCKS 5 daemon:
 Error: User or password can't be blank
Synchronizing state of sockd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable sockd
 Dante Server Install Failed!

 Usage: /etc/init.d/sockd {start|stop|restart|reload|status|state|adduser|deluser|tail|conf|update}
root@cavpn:/home/hsn# /etc/init.d/sockd
 Usage: /etc/init.d/sockd {start|stop|restart|reload|status|state|adduser|deluser|tail|conf|update}
root@cavpn:/home/hsn# /etc/init.d/sockd start
Starting Dante SOCKS 5 daemon:
Danted Server [ Start Failed ]

**Comment by a-kon** [comment]
I got the same issue.

Resolved it with these steps:
1. Run command from [this post](https://github.com/Lozy/danted/issues/55#issuecomment-423787938).
**Input:**
```
bash install.sh -p
```
**Output**:
```
Adding User For Dante SOCKS 5 daemon:
Error: User or password can't be blank
Synchronizing state of sockd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable sockd
Dante Server Install Failed!
```

2. `/etc/init.d/sockd` is up and running, even if you had an error. Now create the user
**Input:** 
```
/etc/init.d/sockd adduser USER_NAME USER_PASSWORD
```
```
Adding User For Dante SOCKS 5 daemon:
Warning: Password truncated to 8 characters by CRYPT algorithm.
Adding password for user USER_NAME
```

3. The user has been created. We can run `bash install.sh -p` one more time.
**Input:**
```
bash install.sh -p
```
**Output:**
```
Current OS: Ubuntu 18.04.3 LTS
Current Options: -p

[Warning] dante sockd already install.
```

4. Everything is fine, run `/etc/init.d/sockd status` to be sure.
**Input:**
```
/etc/init.d/sockd status
```
**Output:**
```
+-----------------------------------------+
 Dante Server [ Running ]
+-----------------------------------------+
 Dante Version:     sockd: dante v1.3.2
 Socks5 Info:
                    YOUR_ADDRESS:YOUR_PORT
 Socks5 User:       USER_NAME
+_________________________________________+
```

5. Done
![image](https://user-images.githubusercontent.com/37555845/72347231-b712da00-36e8-11ea-91b3-76c1922ccda0.png)
