### ISSUE TITLE
Service is Running,but I cant connect to socks with telegram

### ISSUE THREAD

**Issue by mohamadali1374** [Lozy/danted#58]
Hi
I Install danted and run it. also I created a user.

but, I cant connect to socks with telegram.
also I get tails:

Sep 23 12:38:04 (1537720684.927471) sockd[21581]: info: pass(1): tcp/connect [: pam%yaali@5.119.195.179.52809 88.99.73.165.2016 -> 88.99.73.165.52809 149.154.167.91.44

please help me to fix it. 

thanks

**Comment by vEonz121** [comment]
I also have this issue.

My Dante config is:
```
logoutput: syslog
user.privileged: root
user.unprivileged: nobody

# The listening network interface or address.
internal: 0.0.0.0 port=1080

# The proxying network interface or address.
external: eth0

# socks-rules determine what is proxied through the external interface.
socksmethod: username

client pass {
from: 0.0.0.0/0 to: 0.0.0.0/0
}

socks pass {
from: 0.0.0.0/0 to: 0.0.0.0/0
protocol: tcp udp
log: connect disconnect
}
```

I have allowed incoming connections for port 1080 using `sudo ufw allow 1080`.
the VPS is a VM running in Azure, so I also allowed incoming connections from any source for the port 1080 on the Azure platform.

the service is perfectly running on the VPS, here is what I get with that config after running `sudo systemctl restart danted`:

```
● danted.service - SOCKS (v4 and v5) proxy daemon (danted)
     Loaded: loaded (/lib/systemd/system/danted.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2023-01-01 11:54:13 UTC; 25s ago
```

I tested the socks server on the VPS itself using `curl -v -x socks5://myusername:mypassword@0.0.0.0:1080 https://www.google.com/`

and I DO get a response.

But when I connect to my VPS from a remote client using `curl -v -x socks5://myusername:mypassword@[VPS PUBLIC IP ADDRESS]:1080 https://www.google.com/`

I do not get a response, instead it times out.

Port checker from remote client also says the port 1080 for VPS is closed. even after I allowed it using ufw and on azure... 

can I receive some assistance with this?
