### ISSUE TITLE
start-stop-daemon not exist!

### ISSUE THREAD

**Issue by Mehranp** [Lozy/danted#60]
Hello Friends ,
plz help me to solve this error 

Restarting Dante SOCKS 5 daemon:
start-stop-daemon not exist!
start-stop-daemon not exist!
 Dante Server Install Failed!

 Usage: /etc/init.d/sockd {start|stop|restart|reload|status|state|adduser|deluser|tail|conf|update}

**Comment by Lozy** [comment]
Hi, plz show me more detail:

1. os
2. os_version

I guess start-stop-daemon is missing.
