### ISSUE TITLE
Add root check

### ISSUE THREAD

**Issue by xsname** [Lozy/danted#67]
Hi,

I just noticed that your script doesn't check if we are running the install command as root or regular user. This check must be added and if a person run the install.sh as regular user then the script must guide him/her to run the script as root and end itself.

**Comment by Lozy** [comment]
Suggest accepted!

**Comment by Lozy** [comment]
add root check [commit](https://github.com/Lozy/danted/commit/0c29075b9605823e966c9bf9987399323da6727f)
