### ISSUE TITLE
安装失败 Server Install Fail Too many levels of symbolic links

### ISSUE THREAD

**Issue by usbiz** [Lozy/danted#69]
服务器258个ip
linux版本  centos 7.6.1810（py2.7.5）

安装就出现这个错误

Adding User For Dante SOCKS 5 daemon:
Adding password for user hisock5
Failed to execute operation: Too many levels of symbolic links
Restarting sockd (via systemctl):                          [  OK  ]
 Dante Server Install Failed!

**Comment by tndvnn** [comment]
I Think SCRIPT_SERVER="https://public.sockd.info" is not working

**Comment by Lozy** [comment]
Fixed. Sorry for this issue.
