### ISSUE TITLE
新出的老问题--安装失败（New serious problems-installation failed）

### ISSUE THREAD

**Issue by lhuiqing** [Lozy/danted#70]
最近突然出现的问题，试过换各种系统，换vps，推测是某个网站链接不上了，然后少了文件，安装失败了。再已经关闭的问题里，我找到了一样的问题，并且作者说是dns失效了。

Recently, a sudden problem occurred. I tried changing various systems and changing vps. It is speculated that a certain website could not be connected, and then there were fewer files and the installation failed. In the closed question, I found the same problem, and the author said that dns is invalid.

已加载插件：fastestmirror
base                                                                                | 3.6 kB  00:00:00     
extras                                                                              | 2.9 kB  00:00:00     
updates                                                                             | 2.9 kB  00:00:00     
updates/7/x86_64/primary_db                                                         | 6.7 MB  00:00:20     
Loading mirror speeds from cached hostfile
 * base: mirror01.idc.hinet.net
 * extras: mirror01.idc.hinet.net
 * updates: ftp.tc.edu.tw
软件包 gcc-4.8.5-39.el7.x86_64 已安装并且是最新版本
没有可用软件包 g++。
软件包 1:make-3.82-24.el7.x86_64 已安装并且是最新版本
软件包 2:vim-enhanced-7.4.629-6.el7.x86_64 已安装并且是最新版本
软件包 pam-devel-1.1.8-22.el7.x86_64 已安装并且是最新版本
软件包 tcp_wrappers-devel-7.6-77.el7.x86_64 已安装并且是最新版本
软件包 unzip-6.0-20.el7.x86_64 已安装并且是最新版本
软件包 httpd-tools-2.4.6-90.el7.centos.x86_64 已安装并且是最新版本
无须任何处理
已加载插件：fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.hostinginside.com
 * extras: centos.mirror.hostinginside.com
 * updates: ftp.tc.edu.tw
软件包 gcc-4.8.5-39.el7.x86_64 已安装并且是最新版本
没有可用软件包 g++。
软件包 1:make-3.82-24.el7.x86_64 已安装并且是最新版本
没有可用软件包 libpam-dev。
没有可用软件包 libwrap0-dev。
无须任何处理

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
bash: 第 284 行:cd: dante-1.3.2.tar.gz: 不是目录
make: *** 没有指明目标并且找不到 makefile。 停止。
Failed to execute operation: Too many levels of symbolic links
 Dante Server Install Failed!

**Comment by lhuiqing** [comment]
这个是链接
https://github.com/Lozy/danted/issues/27#issuecomment-333289457

https://github.com/Lozy/danted/issues/27#issuecomment-333420846

**Comment by Lozy** [comment]
> 这个是链接
> [#27 (comment)](https://github.com/Lozy/danted/issues/27#issuecomment-333289457)
> 
> [#27 (comment)](https://github.com/Lozy/danted/issues/27#issuecomment-333420846)

Sorry. 迁移了一下域名. DNS解析失效了. 已经修复.

**Comment by lhuiqing** [comment]
太好了，这个脚本真的 真的 非常方便 也非常好用  要是没有这个脚本搭socks5得多费不少劲！
