### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by tndvnn** [Lozy/danted#73]
Hi Lozy,

Can you support the installation with ipv6?

Thank you

**Comment by tndvnn** [comment]
Hello Lozy

**Comment by Lozy** [comment]
> Hi Lozy,
> 
> Can you support the installation with ipv6?
> 
> Thank you

Working on this. Need to upgrade to 1.4.3 with new config.

**Comment by Lozy** [comment]
> Hi Lozy,
> 
> Can you support the installation with ipv6?
> 
> Thank you

Replace `INTERFACE` bellow to your server's nic name, for example eth0.

```
bash install.sh --ip="INTERFACE" --port=2016 --user=sockd --passwd=sockd --version=1.4.2 
```

**Comment by cfcboy** [comment]
Thanks.

> > Hi Lozy,
> > Can you support the installation with ipv6?
> > Thank you
> 
> Replace `INTERFACE` bellow to your server's nic name, for example eth0.
> 
> ```
> bash install.sh --ip="INTERFACE" --port=2016 --version=1.4.2  \
>             --user=sockd --passwd=sockd 
> ```
