### ISSUE TITLE
docker udp

### ISSUE THREAD

**Issue by yl-yue** [Lozy/danted#76]
danted 提供 docker 支持，真的非常方便。
但测试udp时发现建立的端口时随机的，便不能进行docker端口映射，所有测试UDP转发...未通过!

Danted provides docker support, which is really convenient.
However, when the established port is found to be random when testing udp, docker port mapping cannot be carried out, and all test udp forwarding...Failed!

**Comment by Lozy** [comment]
Listen的端口是 2020, 是固定的.  有两个地方可以修改这个端口

- [sockd.conf 配置文件](https://github.com/Lozy/danted/blob/master/docker-1.4.2/conf/sockd.conf), 启动实例的时候 可以指定配置 
- docker-compose端口映射 // docker run 指定的端口

外部测试使用 curl (记得带用户名+密码, 记得重置密码)

> curl https://ifconfig.co --socks5   X.X.X.X:2020 --proxy-user sockd:sockd

**Comment by yl-yue** [comment]
> Listen的端口是 2020, 是固定的. 有两个地方可以修改这个端口
> 
> * [sockd.conf 配置文件](https://github.com/Lozy/danted/blob/master/docker-1.4.2/conf/sockd.conf), 启动实例的时候 可以指定配置
> * docker-compose端口映射 // docker run 指定的端口
> 
> 外部测试使用 curl (记得带用户名+密码, 记得重置密码)
> 
> > curl https://ifconfig.co --socks5   X.X.X.X:2020 --proxy-user sockd:sockd

------

你好！我采用的是 docker 部署，将默认的 2020 端口同时映射了 `udp/tcp` 协议，通过 SSTap 工具做 udp 测试时发现udp建立的隧道是动态的，但这个端口我并没有做docker映射。

测试结果如下：
![image](https://user-images.githubusercontent.com/39790401/79228087-78c9ba00-7e93-11ea-8ed6-bd443fa68975.png)

![image](https://user-images.githubusercontent.com/39790401/79228225-aca4df80-7e93-11ea-927a-3eabad41c3f0.png)

![image](https://user-images.githubusercontent.com/39790401/79228007-5cc61880-7e93-11ea-8292-b03e219ed0da.png)

**Comment by Lozy** [comment]
![image](https://user-images.githubusercontent.com/4269977/79289879-291fd880-7efd-11ea-9a54-fcec0adace1e.png)

感觉你的配置是不是用ss ? 这个不是 shadowsocks 哦~

**Comment by yl-yue** [comment]
> ![image](https://user-images.githubusercontent.com/4269977/79289879-291fd880-7efd-11ea-9a54-fcec0adace1e.png)
> 
> 感觉你的配置是不是用ss ? 这个不是 shadowsocks 哦~

我是把容器的2020端口映射到宿主机1080端口上面，所以服务器的IP与端口并没有填错。同时我又测试了下容器与宿主机端口保持一直，但还是不支持udp代理。

![image](https://user-images.githubusercontent.com/39790401/79320895-1a591600-7f3d-11ea-8aae-d2d7450033e7.png)

同时我发现这个docker镜像做socks5代理效果不是很好，有延迟与断开连接的现象发生。（对比docker镜像：https://hub.docker.com/r/serjs/go-socks5-proxy）
在这里我还想提出几点建议：
- 期望docker支持环境变量注入方式（如：用户数据、端口数据），我在使用 `k8s -v` 这种方式做数据挂载的时候容器一直启不起来。

**Comment by Advanced-noob** [comment]
danted官方版本可以使用`udp.portrange: 52221-52229`这样的语句来限制udp随机端口的范围，我就是这样然后做了10个端口映射
![65MAI3X2)D2L4`V7 WH7QD](https://user-images.githubusercontent.com/28567043/83027705-04259600-a063-11ea-916b-71cd0dd86387.png)
但是这个脚本安装的danted配置文件并不能正常使用该语句，启动不会报错，可是udp端口绑定过程会出错
![}1G}}H}2)S4$P8TEQTCPZL9](https://user-images.githubusercontent.com/28567043/83027785-1dc6dd80-a063-11ea-933d-63c135274b67.png)

**Comment by yl-yue** [comment]
关联 #80
