### ISSUE TITLE
部分代理软件使用不了

### ISSUE THREAD

**Issue by xxHjx** [Lozy/danted#77]
作者你好，我使用dante搭建的服务 使用某些测试代理软件错误 有的就可以 代理失败看日志没有也没有ip

**Comment by Lozy** [comment]
因为没有具体的信息, 猜测可能如下

1. socks5 需要用户认证, 部分软件可能不支持, 例如浏览器
2. `GFW` 防火墙可能会过滤, 如果你在境内使用境外的socks5 会遇到这种情况.

**Comment by xxHjx** [comment]
感谢！ 还有一个问题 就是 这个支持多少并发呀  有没有参数控制

**Comment by Lozy** [comment]
> 感谢！ 还有一个问题 就是 这个支持多少并发呀 有没有参数控制

可以看官方的报告 [dante_performance_1.4.0](https://www.inet.no/dante/doc/1.4.x/dante_performance_1.4.0.pdf)
