### ISSUE TITLE
CPU占用

### ISSUE THREAD

**Issue by boy7928** [Lozy/danted#8]
启动后 多用户使用 CPU会跑满 拖挂机器 8核心 E5

**Comment by Lozy** [comment]
不知道你的用户量是多少？
如果有大量用户，可以调整启动的参数 -N fork多个进程 （目前默认是1）
另外，

- 看一下IO 是否有压力，关闭一下日志测试一下
- 看一下认证方式是否为PAM，是否存在 ulimit 问题
