### ISSUE TITLE
无法正常限制udp端口范围

### ISSUE THREAD

**Issue by Advanced-Noob** [Lozy/danted#80]
danted官方版本可以使用`udp.portrange: 52221-52229`这样的语句来限制udp随机端口的范围，我就是这样然后做了10个端口映射
![65MAI3X2)D2L4`V7 WH7QD](https://user-images.githubusercontent.com/28567043/83028216-b2314000-a063-11ea-9c72-4236e3d9d7f8.png)
但是这个脚本安装的danted配置文件并不能正常使用该语句，启动不会报错，可是udp端口绑定过程会出错
![}1G}}H}2)S4$P8TEQTCPZL9](https://user-images.githubusercontent.com/28567043/83028232-b6f5f400-a063-11ea-95d8-62d8f69b1a49.png)
希望作者抽空看一下此问题，谢谢

**Comment by Advanced-noob** [comment]
如果删掉此行，每次建立udp链接都会绑定在随机的端口，不方便端口映射与防火墙的设置
![0AK`6 {I_{O96Z(JF(%T3ED](https://user-images.githubusercontent.com/28567043/83028842-89f61100-a064-11ea-90db-4599452893a4.png)
