### ISSUE TITLE
下载不了文件.

### ISSUE THREAD

**Issue by 775083111** [Lozy/danted#84]
6[root@192 ~]# wget --no-check-certificate https://raw.github.com/Lozy/danted/master/install.sh -O install.sh
--2020-11-23 08:31:10--  https://raw.github.com/Lozy/danted/master/install.sh
正在解析主机 raw.github.com (raw.github.com)... 151.101.108.133
正在连接 raw.github.com (raw.github.com)|151.101.108.133|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 301 Moved Permanently
位置：https://raw.githubusercontent.com/Lozy/danted/master/install.sh [跟随至新的 URL]
--2020-11-23 08:31:11--  https://raw.githubusercontent.com/Lozy/danted/master/install.sh
正在解析主机 raw.githubusercontent.com (raw.githubusercontent.com)... 0.0.0.0, ::
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|0.0.0.0|:443... 失败：拒绝连接。
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|::|:443... 失败：拒绝连接。

**Comment by chenmoaaaa** [comment]
看看你的机器能不能访问Git
