### ISSUE TITLE
好像有服务器包坏了 大佬能不能检修下 一直用你的脚本 现在多IP机器都装不上了

### ISSUE THREAD

**Issue by laikening** [Lozy/danted#91]
好像有服务器包坏了 大佬能不能检修下 一直用你的脚本 现在多IP机器都装不上了

**Comment by isuiyuan8** [comment]
同求解

**Comment by laikening** [comment]
> 同求解

服务器包恢复了啊 现在可以用了 坏了2天 应该是服务器到期了 要谢谢大佬的脚本

**Comment by isuiyuan8** [comment]
恢复了但是不知道应该怎么弄镜像了 万一还出这个问题好难受的

**Comment by laikening** [comment]
> 恢复了但是不知道应该怎么弄镜像了 万一还出这个问题好难受的

我已经备份了一份了 作者的应该是年缴的吧 起码1年不用担心了  1年后如果还不能用来这回复我 我发给你就好了

**Comment by isuiyuan8** [comment]
我也备份了但是我改啦脚本域名后发现也是搭建不了不知道哪里问题

**Comment by laikening** [comment]
> 我也备份了但是我改啦脚本域名后发现也是搭建不了不知道哪里问题

你学作者啊 搭建个h5ai的网站 我学他搭建的h5ai之后 完全用我自己的也可用了

**Comment by isuiyuan8** [comment]
我把他脚本里面的文件都保存到我网站上了但是依然不行脚本也修改了估计是有部分没修改好https://public.sockd.info 这个网站的文件都保存了域名也都替换了

**Comment by laikening** [comment]
> 我把他脚本里面的文件都保存到我网站上了但是依然不行脚本也修改了估计是有部分没修改好https://public.sockd.info 这个网站的文件都保存了域名也都替换了

我替换了后成功了 不知道你问题出在哪 可以加我q529597146 交流交流

**Comment by isuiyuan8** [comment]
已添加

**Comment by nxtreaming** [comment]
除了1.4.3在服务器上没有，需要自己额外下载，1.3.2和1.4.2都可以用啊

**Comment by Lozy** [comment]
服务器过期了。已经 fix.
