### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by Monster-2019** [Lozy/danted#98]
![image](https://user-images.githubusercontent.com/44371432/176083529-870bd7d9-0c41-4f4c-93fa-1e64a4846c95.png)
配置
![image](https://user-images.githubusercontent.com/44371432/176083616-ad9d9af8-f6b8-46e2-ad1f-8c2934586a99.png)
日志
![image](https://user-images.githubusercontent.com/44371432/176083710-fa9ef9f9-9258-4c67-a9ce-83ae9e96cdd0.png)

**Comment by Lozy** [comment]
看报错无法BIND地址，是否地址写错，或者端口已经被分配占用
